--DDL
bq mk -t ulta_base_customer.CREDIT_CARD_ACCOUNT_DIMENSION CREDIT_CARD_ACCOUNT_KEY:INTEGER, ACCEPTANCE_REFERRAL_CODE:STRING, ACCOUNT_INDICATOR_01:STRING, ACCOUNT_INDICATOR_02:STRING, ACCOUNT_INDICATOR_03:STRING, ACCOUNT_NUMBER:INTEGER, ACTIVATION_FLAG:STRING, ACTIVE_INACTIVE_INDICATOR:STRING, ADDRESS_CHANGE:DATE, ADOBE_ACTIVE_INACTIVE_INDICATOR:STRING, AMOUNT_OF_LAST_PAYMENT:FLOAT, AMOUNT_OF_LAST_PURCHASE:FLOAT, APPLICATION_NUMBER:STRING, APPLICATION_SOURCE_CODE:INTEGER, BALANCE_ALL_PLANS:FLOAT, BIRTH_DATE:DATE, CARD_EXPIRE_DATE:DATE(YYYY-MM-DD), CARD_ISSUE_DATE:DATE(YYYY-MM-DD), CARD_NUMBER:STRING, CLERK_NUMBER:STRING, CLOSED_DATE:DATE(YYYY-MM-DD), COBRAND_EXPIRATION_DATE:DATE(YYYY-MM-DD), CREATED_DATE:TIMESTAMP(YYYY-MM-DD:hh:mm:ss), CREDIT_LIMIT:FLOAT, CREDIT_TERM_NUMBER:INTEGER, CREDIT_TERM_NUMBER_CARD_TYPE:STRING, CURRENT_OTB:INTEGER, CYCLE_NUMBER:INTEGER, CYCLE_UPDATE_DATE:DATE(YYYY-MM-DD), DIVISION_NUMBER:INTEGER, DO_NOT_DIRECT_MAIL:STRING, DO_NOT_SELL_NAME:STRING, DO_NOT_STATEMENT_INSERT:STRING, DO_NOT_TELEMARKET:STRING, EMAIL_CHANGE_DATE:DATE(YYYY-MM-DD), EMAIL_MARKETING_CONSENT_INDICATOR:STRING, EMAIL_OPT_DATE:DATE(YYYY-MM-DD), ESTATEMENT_CHANGE_DATE:DATE(YYYY-MM-DD), ESTATEMENT_INDICATOR:STRING, FIRST_NAME:STRING, FOREIGN_MAP_CODE:STRING, INDICATOR:STRING, LAST_4_DIGITS_OF_ACCOUNT_NUMBER:STRING, LAST_MODIFIED:TIMESTAMP(YYYY-MM-DD:hh:mm:ss), LAST_NAME:STRING, LAST_PAYMENT_DATE:DATE(YYYY-MM-DD), LAST_PURCHASE_DATE:DATE(YYYY-MM-DD), LAST_RETURN_DATE:DATE(YYYY-MM-DD), LOGO:INTEGER, LOGO_CHANGE_DATE:DATE(YYYY-MM-DD), MARKETING_PROMO_FLAG:INTEGER, MGN_ID:STRING, MIDDLE_NAME:STRING, MOBILE_PUSH_CONSENT_INDICATOR:STRING, NEW_ACCOUNT_CLERK_NUMBER:INTEGER, NUMBER_OF_CARDS_ISSUED:INTEGER, OPEN_DATE:DATE(YYYY-MM-DD), PERSON_ID:STRING, PRESCREEN_ID:INTEGER, PREVIOUS_ACCOUNT_NUMBER:INTEGER, PREVIOUS_CREDIT_TERM_NUMBER:INTEGER, PROMOTABILITY_INDICATOR:STRING, RECOURSE_INDICATOR:STRING, RETURN_MAIL_INDICATOR:STRING, SLANGUAGEINDICATOR:STRING, SMS_MARKETING_CONSENT_INDICATOR:STRING, SMS_SERVICE_CONSENT_INDICATOR:STRING, SPAM_INDICATOR:STRING, STATEMENT_SUBSCRIPTION_INDICATOR:STRING, SUR_TITLE:STRING, TRANSFERRED_FROM_ACCOUNT_NUMBER:INTEGER, YTD_PURCHASE_AMOUNT:FLOAT, EMAIL:STRING, COMPLETE_NUMBER:STRING, COMPLETE_NUMBER_1:STRING, COMPLETE_NUMBER_2:STRING, INDIVIDUAL_ID:STRING, ADDRESS_LINE_1:STRING, CITY_NAME:STRING, STATE:STRING, POSTAL_CODE:STRING, POSTAL_CODE_EXTENSION:STRING, BUSINESS_UNIT_ID:STRING, INDIVIDUAL_KEY:INTEGER

bq mk -t ulta_base_customer.CREDIT_CARD_ACCOUNT_DIMENSION_UNCHANGED CREDIT_CARD_ACCOUNT_KEY:INTEGER, ACCEPTANCE_REFERRAL_CODE:STRING, ACCOUNT_INDICATOR_01:STRING, ACCOUNT_INDICATOR_02:STRING, ACCOUNT_INDICATOR_03:STRING, ACCOUNT_NUMBER:INTEGER, ACTIVATION_FLAG:STRING, ACTIVE_INACTIVE_INDICATOR:STRING, ADDRESS_CHANGE:DATE, ADOBE_ACTIVE_INACTIVE_INDICATOR:STRING, AMOUNT_OF_LAST_PAYMENT:FLOAT, AMOUNT_OF_LAST_PURCHASE:FLOAT, APPLICATION_NUMBER:STRING, APPLICATION_SOURCE_CODE:INTEGER, BALANCE_ALL_PLANS:FLOAT, BIRTH_DATE:DATE, CARD_EXPIRE_DATE:DATE(YYYY-MM-DD), CARD_ISSUE_DATE:DATE(YYYY-MM-DD), CARD_NUMBER:STRING, CLERK_NUMBER:STRING, CLOSED_DATE:DATE(YYYY-MM-DD), COBRAND_EXPIRATION_DATE:DATE(YYYY-MM-DD), CREATED_DATE:TIMESTAMP(YYYY-MM-DD:hh:mm:ss), CREDIT_LIMIT:FLOAT, CREDIT_TERM_NUMBER:INTEGER, CREDIT_TERM_NUMBER_CARD_TYPE:STRING, CURRENT_OTB:INTEGER, CYCLE_NUMBER:INTEGER, CYCLE_UPDATE_DATE:DATE(YYYY-MM-DD), DIVISION_NUMBER:INTEGER, DO_NOT_DIRECT_MAIL:STRING, DO_NOT_SELL_NAME:STRING, DO_NOT_STATEMENT_INSERT:STRING, DO_NOT_TELEMARKET:STRING, EMAIL_CHANGE_DATE:DATE(YYYY-MM-DD), EMAIL_MARKETING_CONSENT_INDICATOR:STRING, EMAIL_OPT_DATE:DATE(YYYY-MM-DD), ESTATEMENT_CHANGE_DATE:DATE(YYYY-MM-DD), ESTATEMENT_INDICATOR:STRING, FIRST_NAME:STRING, FOREIGN_MAP_CODE:STRING, INDICATOR:STRING, LAST_4_DIGITS_OF_ACCOUNT_NUMBER:STRING, LAST_MODIFIED:TIMESTAMP(YYYY-MM-DD:hh:mm:ss), LAST_NAME:STRING, LAST_PAYMENT_DATE:DATE(YYYY-MM-DD), LAST_PURCHASE_DATE:DATE(YYYY-MM-DD), LAST_RETURN_DATE:DATE(YYYY-MM-DD), LOGO:INTEGER, LOGO_CHANGE_DATE:DATE(YYYY-MM-DD), MARKETING_PROMO_FLAG:INTEGER, MGN_ID:STRING, MIDDLE_NAME:STRING, MOBILE_PUSH_CONSENT_INDICATOR:STRING, NEW_ACCOUNT_CLERK_NUMBER:INTEGER, NUMBER_OF_CARDS_ISSUED:INTEGER, OPEN_DATE:DATE(YYYY-MM-DD), PERSON_ID:STRING, PRESCREEN_ID:INTEGER, PREVIOUS_ACCOUNT_NUMBER:INTEGER, PREVIOUS_CREDIT_TERM_NUMBER:INTEGER, PROMOTABILITY_INDICATOR:STRING, RECOURSE_INDICATOR:STRING, RETURN_MAIL_INDICATOR:STRING, SLANGUAGEINDICATOR:STRING, SMS_MARKETING_CONSENT_INDICATOR:STRING, SMS_SERVICE_CONSENT_INDICATOR:STRING, SPAM_INDICATOR:STRING, STATEMENT_SUBSCRIPTION_INDICATOR:STRING, SUR_TITLE:STRING, TRANSFERRED_FROM_ACCOUNT_NUMBER:INTEGER, YTD_PURCHASE_AMOUNT:FLOAT, EMAIL:STRING, COMPLETE_NUMBER:STRING, COMPLETE_NUMBER_1:STRING, COMPLETE_NUMBER_2:STRING, INDIVIDUAL_ID:STRING, ADDRESS_LINE_1:STRING, CITY_NAME:STRING, STATE:STRING, POSTAL_CODE:STRING, POSTAL_CODE_EXTENSION:STRING, BUSINESS_UNIT_ID:STRING, INDIVIDUAL_KEY:INTEGER


bq mk -t ulta_mart_customer.CREDIT_CARD_ACCOUNT_DIMENSION CREDIT_CARD_ACCOUNT_KEY:INTEGER, ACCEPTANCE_REFERRAL_CODE:STRING, ACCOUNT_INDICATOR_01:STRING, ACCOUNT_INDICATOR_02:STRING, ACCOUNT_INDICATOR_03:STRING, ACCOUNT_NUMBER:INTEGER, ACTIVATION_FLAG:STRING, ACTIVE_INACTIVE_INDICATOR:STRING, ADDRESS_CHANGE:DATE, ADOBE_ACTIVE_INACTIVE_INDICATOR:STRING, AMOUNT_OF_LAST_PAYMENT:FLOAT, AMOUNT_OF_LAST_PURCHASE:FLOAT, APPLICATION_NUMBER:STRING, APPLICATION_SOURCE_CODE:INTEGER, BALANCE_ALL_PLANS:FLOAT, BIRTH_DATE:DATE, CARD_EXPIRE_DATE:DATE(YYYY-MM-DD), CARD_ISSUE_DATE:DATE(YYYY-MM-DD), CARD_NUMBER:STRING, CLERK_NUMBER:STRING, CLOSED_DATE:DATE(YYYY-MM-DD), COBRAND_EXPIRATION_DATE:DATE(YYYY-MM-DD), CREATED_DATE:TIMESTAMP(YYYY-MM-DD:hh:mm:ss), CREDIT_LIMIT:FLOAT, CREDIT_TERM_NUMBER:INTEGER, CREDIT_TERM_NUMBER_CARD_TYPE:STRING, CURRENT_OTB:INTEGER, CYCLE_NUMBER:INTEGER, CYCLE_UPDATE_DATE:DATE(YYYY-MM-DD), DIVISION_NUMBER:INTEGER, DO_NOT_DIRECT_MAIL:STRING, DO_NOT_SELL_NAME:STRING, DO_NOT_STATEMENT_INSERT:STRING, DO_NOT_TELEMARKET:STRING, EMAIL_CHANGE_DATE:DATE(YYYY-MM-DD), EMAIL_MARKETING_CONSENT_INDICATOR:STRING, EMAIL_OPT_DATE:DATE(YYYY-MM-DD), ESTATEMENT_CHANGE_DATE:DATE(YYYY-MM-DD), ESTATEMENT_INDICATOR:STRING, FIRST_NAME:STRING, FOREIGN_MAP_CODE:STRING, INDICATOR:STRING, LAST_4_DIGITS_OF_ACCOUNT_NUMBER:STRING, LAST_MODIFIED:TIMESTAMP(YYYY-MM-DD:hh:mm:ss), LAST_NAME:STRING, LAST_PAYMENT_DATE:DATE(YYYY-MM-DD), LAST_PURCHASE_DATE:DATE(YYYY-MM-DD), LAST_RETURN_DATE:DATE(YYYY-MM-DD), LOGO:INTEGER, LOGO_CHANGE_DATE:DATE(YYYY-MM-DD), MARKETING_PROMO_FLAG:INTEGER, MGN_ID:STRING, MIDDLE_NAME:STRING, MOBILE_PUSH_CONSENT_INDICATOR:STRING, NEW_ACCOUNT_CLERK_NUMBER:INTEGER, NUMBER_OF_CARDS_ISSUED:INTEGER, OPEN_DATE:DATE(YYYY-MM-DD), PERSON_ID:STRING, PRESCREEN_ID:INTEGER, PREVIOUS_ACCOUNT_NUMBER:INTEGER, PREVIOUS_CREDIT_TERM_NUMBER:INTEGER, PROMOTABILITY_INDICATOR:STRING, RECOURSE_INDICATOR:STRING, RETURN_MAIL_INDICATOR:STRING, SLANGUAGEINDICATOR:STRING, SMS_MARKETING_CONSENT_INDICATOR:STRING, SMS_SERVICE_CONSENT_INDICATOR:STRING, SPAM_INDICATOR:STRING, STATEMENT_SUBSCRIPTION_INDICATOR:STRING, SUR_TITLE:STRING, TRANSFERRED_FROM_ACCOUNT_NUMBER:INTEGER, YTD_PURCHASE_AMOUNT:FLOAT, EMAIL:STRING, COMPLETE_NUMBER:STRING, COMPLETE_NUMBER_1:STRING, COMPLETE_NUMBER_2:STRING, INDIVIDUAL_ID:STRING, ADDRESS_LINE_1:STRING, CITY_NAME:STRING, STATE:STRING, POSTAL_CODE:STRING, POSTAL_CODE_EXTENSION:STRING, BUSINESS_UNIT_ID:STRING, INDIVIDUAL_KEY:INTEGER

--1. Step to insert in to stage table
DELETE ulta_base_customer.CREDIT_CARD_ACCOUNT_DIMENSION WHERE TRUE

insert into ulta_base_customer.CREDIT_CARD_ACCOUNT_DIMENSION (CREDIT_CARD_ACCOUNT_KEY,ACCEPTANCE_REFERRAL_CODE,ACCOUNT_INDICATOR_01,ACCOUNT_INDICATOR_02,ACCOUNT_INDICATOR_03,ACCOUNT_NUMBER,ACTIVATION_FLAG, ACTIVE_INACTIVE_INDICATOR,ADDRESS_CHANGE,ADOBE_ACTIVE_INACTIVE_INDICATOR,AMOUNT_OF_LAST_PAYMENT,AMOUNT_OF_LAST_PURCHASE,APPLICATION_NUMBER, APPLICATION_SOURCE_CODE,BALANCE_ALL_PLANS,BIRTH_DATE,CARD_EXPIRE_DATE,CARD_ISSUE_DATE,CARD_NUMBER,CLERK_NUMBER,CLOSED_DATE,COBRAND_EXPIRATION_DATE, CREATED_DATE,CREDIT_LIMIT,CREDIT_TERM_NUMBER,CREDIT_TERM_NUMBER_CARD_TYPE,CURRENT_OTB,CYCLE_NUMBER,CYCLE_UPDATE_DATE,DIVISION_NUMBER, DO_NOT_DIRECT_MAIL,DO_NOT_SELL_NAME,DO_NOT_STATEMENT_INSERT,DO_NOT_TELEMARKET,EMAIL_CHANGE_DATE,EMAIL_MARKETING_CONSENT_INDICATOR,EMAIL_OPT_DATE, ESTATEMENT_CHANGE_DATE,ESTATEMENT_INDICATOR,FIRST_NAME,FOREIGN_MAP_CODE,INDICATOR,LAST_4_DIGITS_OF_ACCOUNT_NUMBER,LAST_MODIFIED,LAST_NAME, LAST_PAYMENT_DATE,LAST_PURCHASE_DATE,LAST_RETURN_DATE,LOGO,LOGO_CHANGE_DATE,MARKETING_PROMO_FLAG,MGN_ID,MIDDLE_NAME,MOBILE_PUSH_CONSENT_INDICATOR, NEW_ACCOUNT_CLERK_NUMBER,NUMBER_OF_CARDS_ISSUED,OPEN_DATE,PERSON_ID,PRESCREEN_ID,PREVIOUS_ACCOUNT_NUMBER,PREVIOUS_CREDIT_TERM_NUMBER, PROMOTABILITY_INDICATOR,RECOURSE_INDICATOR,RETURN_MAIL_INDICATOR,SLANGUAGEINDICATOR,SMS_MARKETING_CONSENT_INDICATOR,SMS_SERVICE_CONSENT_INDICATOR, SPAM_INDICATOR,STATEMENT_SUBSCRIPTION_INDICATOR,SUR_TITLE,TRANSFERRED_FROM_ACCOUNT_NUMBER,YTD_PURCHASE_AMOUNT,EMAIL,COMPLETE_NUMBER,COMPLETE_NUMBER_1, COMPLETE_NUMBER_2,INDIVIDUAL_ID,ADDRESS_LINE_1,CITY_NAME,STATE,POSTAL_CODE,POSTAL_CODE_EXTENSION,BUSINESS_UNIT_ID,INDIVIDUAL_KEY)
Select  NULL as CREDIT_CARD_ACCOUNT_KEY,		-- Not present in STM
		CREDITCARDCUSTOMER.SACCEPTANCEREFERRALCODE as ACCEPTANCE_REFERRAL_CODE,
		CREDITCARDCUSTOMER.SACCOUNTINDICATOR01 as ACCOUNT_INDICATOR_01,
		CREDITCARDCUSTOMER.SACCOUNTINDICATOR02	as	ACCOUNT_INDICATOR_02,
		CREDITCARDCUSTOMER.SACCOUNTINDICATOR03	as	ACCOUNT_INDICATOR_03,
		CREDITCARDCUSTOMER.BIACCOUNTNUMBER	as	ACCOUNT_NUMBER,
		CREDITCARDCUSTOMER.SACTIVATIONFLAG	as	ACTIVATION_FLAG,
		CREDITCARDCUSTOMER.SACTIVEINACTIVEINDICATOR	as	ACTIVE_INACTIVE_INDICATOR,
		CREDITCARDCUSTOMER.TSADDRESSCHANGE as ADDRESS_CHANGE,
		CREDITCARDCUSTOMER.SADOBEACTIVEINACTIVEINDICATOR as ADOBE_ACTIVE_INACTIVE_INDICATOR,
		CREDITCARDCUSTOMER.DAMOUNTOFLASTPAYMENT as AMOUNT_OF_LAST_PAYMENT,
		CREDITCARDCUSTOMER.DAMOUNTOFLASTPURCHASE as AMOUNT_OF_LAST_PURCHASE,
		CREDITCARDCUSTOMER.SAPPLICATIONNUMBER as APPLICATION_NUMBER,
		CREDITCARDCUSTOMER.IAPPLICATIONSOURCECODE as APPLICATION_SOURCE_CODE,
		CREDITCARDCUSTOMER.DBALANCEALLPLANS as BALANCE_ALL_PLANS,
		CREDITCARDCUSTOMER.TSBIRTH as BIRTH_DATE,
		CREDITCARDCUSTOMER.TSCARDEXPIRE as CARD_EXPIRE_DATE,
		CREDITCARDCUSTOMER.TSCARDISSUE as CARD_ISSUE_DATE,
		NULL as CARD_NUMBER,					-- Multiple sources
		CREDITCARDCUSTOMER.SCLERKNUMBER as CLERK_NUMBER,
		CREDITCARDCUSTOMER.TSCLOSED as CLOSED_DATE,
		CREDITCARDCUSTOMER.TSCOBRANDEXPIRATION	as	COBRAND_EXPIRATION_DATE,
		CREDITCARDCUSTOMER.TSCREATED	as	CREATED_DATE,
		CREDITCARDCUSTOMER.DCREDITLIMIT	as	CREDIT_LIMIT,
		CREDITCARDCUSTOMER.ICREDITTERMNUMBER	as	CREDIT_TERM_NUMBER,
		CREDITCARDCUSTOMER.SCREDITTERMNUMBERCARDTYPE	as	CREDIT_TERM_NUMBER_CARD_TYPE,
		CREDITCARDCUSTOMER.ICURRENTOTB	as	CURRENT_OTB,
		CREDITCARDCUSTOMER.ICYCLENUMBER	as	CYCLE_NUMBER,
		CREDITCARDCUSTOMER.TSCYCLEUPDATE	as	CYCLE_UPDATE_DATE,
		CREDITCARDCUSTOMER.BIDIVISIONNUMBER	as	DIVISION_NUMBER	,
		CREDITCARDCUSTOMER.SDONOTDIRECTMAIL	as	DO_NOT_DIRECT_MAIL,
		CREDITCARDCUSTOMER.SDONOTSELLNAME	as	DO_NOT_SELL_NAME,
		CREDITCARDCUSTOMER.SDONOTSTATEMENTINSERT	as	DO_NOT_STATEMENT_INSERT,
		CREDITCARDCUSTOMER.SDONOTTELEMARKET	as	DO_NOT_TELEMARKET,
		CREDITCARDCUSTOMER.TSEMAILCHANGE	as	EMAIL_CHANGE_DATE,
		CREDITCARDCUSTOMER.SEMAILMARKETINGCONSENTINDICATOR	as	EMAIL_MARKETING_CONSENT_INDICATOR,
		CREDITCARDCUSTOMER.TSEMAILOPT	as	EMAIL_OPT_DATE,
		CREDITCARDCUSTOMER.TSESTATEMENTCHANGE	as	ESTATEMENT_CHANGE_DATE,
		CREDITCARDCUSTOMER.SESTATEMENTINDICATOR	as	ESTATEMENT_INDICATOR,
		CREDITCARDCUSTOMER.SFIRSTNAME	as	FIRST_NAME,
		CREDITCARDCUSTOMER.SFOREIGNMAPCODE	as	FOREIGN_MAP_CODE,
		CREDITCARDCUSTOMER.SINDICATOR	as	INDICATOR,
		CREDITCARDCUSTOMER.SLAST4DIGITSOFACCOUNTNUMBER	as	LAST_4_DIGITS_OF_ACCOUNT_NUMBER,
		CREDITCARDCUSTOMER.TSLASTMODIFIED	as	LAST_MODIFIED,
		CREDITCARDCUSTOMER.SLASTNAME	as	LAST_NAME,
		CREDITCARDCUSTOMER.TSLASTPAYMENT	as	LAST_PAYMENT_DATE,
		CREDITCARDCUSTOMER.TSLASTPURCHASE	as	LAST_PURCHASE_DATE,
		CREDITCARDCUSTOMER.TSLASTRETURN	as	LAST_RETURN_DATE,
		CREDITCARDCUSTOMER.ILOGO	as	LOGO,
		CREDITCARDCUSTOMER.TSLOGOCHANGE	as	LOGO_CHANGE_DATE,
		CREDITCARDCUSTOMER.IMARKETINGPROMOFLAG	as	MARKETING_PROMO_FLAG,
		CREDITCARDCUSTOMER.SMGNID	as	MGN_ID,
		CREDITCARDCUSTOMER.SMIDDLEINITIAL	as	MIDDLE_NAME,
		CREDITCARDCUSTOMER.SMOBILEPUSHCONSENTINDICATOR	as	MOBILE_PUSH_CONSENT_INDICATOR,
		CREDITCARDCUSTOMER.INEWACCOUNTCLERKNUMBER	as	NEW_ACCOUNT_CLERK_NUMBER,
		CREDITCARDCUSTOMER.INUMBEROFCARDSISSUED	as	NUMBER_OF_CARDS_ISSUED,
		CREDITCARDCUSTOMER.TSOPEN	as	OPEN_DATE,
		CREDITCARDCUSTOMER.SPERSONID	as	PERSON_ID,
		CREDITCARDCUSTOMER.BIPRESCREENID	as	PRESCREEN_ID,
		CREDITCARDCUSTOMER.IPREVIOUSACCOUNTNUMBER	as	PREVIOUS_ACCOUNT_NUMBER	,
		CREDITCARDCUSTOMER.IPREVIOUSCREDITTERMNUMBER	as	PREVIOUS_CREDIT_TERM_NUMBER,
		CREDITCARDCUSTOMER.SPROMOTABILITYINDICATOR	as	PROMOTABILITY_INDICATOR,
		CREDITCARDCUSTOMER.SRECOURSEINDICATOR	as	RECOURSE_INDICATOR,
		CREDITCARDCUSTOMER.SRETURNMAILINDICATOR	as	RETURN_MAIL_INDICATOR,
		CREDITCARDCUSTOMER.SLANGUAGEINDICATOR	as	SLANGUAGEINDICATOR,
		CREDITCARDCUSTOMER.SSMSMARKETINGCONSENTINDICATOR	as	SMS_MARKETING_CONSENT_INDICATOR,
		CREDITCARDCUSTOMER.SSMSSERVICECONSENTINDICATOR	as	SMS_SERVICE_CONSENT_INDICATOR,
		CREDITCARDCUSTOMER.SSPAMINDICATOR	as	SPAM_INDICATOR,
		CREDITCARDCUSTOMER.SSTATEMENTSUBSCRIPTIONINDICATOR	as	STATEMENT_SUBSCRIPTION_INDICATOR,
		CREDITCARDCUSTOMER.SSURTITLE	as	SUR_TITLE,	
		CREDITCARDCUSTOMER.ITRANSFERREDFROMACCOUNTNUMBER	as	TRANSFERRED_FROM_ACCOUNT_NUMBER,
		CREDITCARDCUSTOMER.DYTDPURCHASEAMOUNT	as	YTD_PURCHASE_AMOUNT,		
		NULL as EMAIL,                          -- Multiple sources
		NULL as COMPLETE_NUMBER,                -- Multiple sources
		NULL as COMPLETE_NUMBER_1,              -- Multiple sources
		NULL as COMPLETE_NUMBER_2,              -- Multiple sources
		NULL as INDIVIDUAL_ID,                  -- Multiple sources
		NULL as ADDRESS_LINE_1,                 -- Multiple sources
		NULL as CITY_NAME,                      -- Multiple sources
		NULL as STATE,                          -- Multiple sources
		NULL as POSTAL_CODE,                    -- Multiple sources
		NULL as POSTAL_CODE_EXTENSION,          -- Multiple sources
		NULL as BUSINESS_UNIT_ID,               -- Multiple sources
		NULL as INDIVIDUAL_KEY,                 -- Member key attribute
		
FROM ULTA_LAND.CREDITCARDCUSTOMER 


--2. populate unchanged stage table
DELETE ulta_base_customer.CREDIT_CARD_ACCOUNT_DIMENSION_UNCHANGED WHERE TRUE

insert into ulta_base_customer.CREDIT_CARD_ACCOUNT_DIMENSION_UNCHANGED (CREDIT_CARD_ACCOUNT_KEY,ACCEPTANCE_REFERRAL_CODE,ACCOUNT_INDICATOR_01,ACCOUNT_INDICATOR_02,ACCOUNT_INDICATOR_03,ACCOUNT_NUMBER,ACTIVATION_FLAG, ACTIVE_INACTIVE_INDICATOR,ADDRESS_CHANGE,ADOBE_ACTIVE_INACTIVE_INDICATOR,AMOUNT_OF_LAST_PAYMENT,AMOUNT_OF_LAST_PURCHASE,APPLICATION_NUMBER, APPLICATION_SOURCE_CODE,BALANCE_ALL_PLANS,BIRTH_DATE,CARD_EXPIRE_DATE,CARD_ISSUE_DATE,CARD_NUMBER,CLERK_NUMBER,CLOSED_DATE,COBRAND_EXPIRATION_DATE, CREATED_DATE,CREDIT_LIMIT,CREDIT_TERM_NUMBER,CREDIT_TERM_NUMBER_CARD_TYPE,CURRENT_OTB,CYCLE_NUMBER,CYCLE_UPDATE_DATE,DIVISION_NUMBER, DO_NOT_DIRECT_MAIL,DO_NOT_SELL_NAME,DO_NOT_STATEMENT_INSERT,DO_NOT_TELEMARKET,EMAIL_CHANGE_DATE,EMAIL_MARKETING_CONSENT_INDICATOR,EMAIL_OPT_DATE, ESTATEMENT_CHANGE_DATE,ESTATEMENT_INDICATOR,FIRST_NAME,FOREIGN_MAP_CODE,INDICATOR,LAST_4_DIGITS_OF_ACCOUNT_NUMBER,LAST_MODIFIED,LAST_NAME, LAST_PAYMENT_DATE,LAST_PURCHASE_DATE,LAST_RETURN_DATE,LOGO,LOGO_CHANGE_DATE,MARKETING_PROMO_FLAG,MGN_ID,MIDDLE_NAME,MOBILE_PUSH_CONSENT_INDICATOR, NEW_ACCOUNT_CLERK_NUMBER,NUMBER_OF_CARDS_ISSUED,OPEN_DATE,PERSON_ID,PRESCREEN_ID,PREVIOUS_ACCOUNT_NUMBER,PREVIOUS_CREDIT_TERM_NUMBER, PROMOTABILITY_INDICATOR,RECOURSE_INDICATOR,RETURN_MAIL_INDICATOR,SLANGUAGEINDICATOR,SMS_MARKETING_CONSENT_INDICATOR,SMS_SERVICE_CONSENT_INDICATOR, SPAM_INDICATOR,STATEMENT_SUBSCRIPTION_INDICATOR,SUR_TITLE,TRANSFERRED_FROM_ACCOUNT_NUMBER,YTD_PURCHASE_AMOUNT,EMAIL,COMPLETE_NUMBER,COMPLETE_NUMBER_1, COMPLETE_NUMBER_2,INDIVIDUAL_ID,ADDRESS_LINE_1,CITY_NAME,STATE,POSTAL_CODE,POSTAL_CODE_EXTENSION,BUSINESS_UNIT_ID,INDIVIDUAL_KEY)
SELECT mart.CREDIT_CARD_ACCOUNT_KEY,mart.ACCEPTANCE_REFERRAL_CODE,mart.ACCOUNT_INDICATOR_01,mart.ACCOUNT_INDICATOR_02,mart.ACCOUNT_INDICATOR_03,mart.ACCOUNT_NUMBER,mart.ACTIVATION_FLAG,mart.ACTIVE_INACTIVE_INDICATOR,mart.ADDRESS_CHANGE,mart.ADOBE_ACTIVE_INACTIVE_INDICATOR,mart.AMOUNT_OF_LAST_PAYMENT,mart.AMOUNT_OF_LAST_PURCHASE,mart.APPLICATION_NUMBER,mart.APPLICATION_SOURCE_CODE,mart.BALANCE_ALL_PLANS,mart.BIRTH_DATE,mart.CARD_EXPIRE_DATE,mart.CARD_ISSUE_DATE,mart.CARD_NUMBER,mart.CLERK_NUMBER,mart.CLOSED_DATE,mart.COBRAND_EXPIRATION_DATE,mart.CREATED_DATE,mart.CREDIT_LIMIT,mart.CREDIT_TERM_NUMBER,mart.CREDIT_TERM_NUMBER_CARD_TYPE,mart.CURRENT_OTB,mart.CYCLE_NUMBER,mart.CYCLE_UPDATE_DATE,mart.DIVISION_NUMBER,mart.DO_NOT_DIRECT_MAIL,mart.DO_NOT_SELL_NAME,mart.DO_NOT_STATEMENT_INSERT,mart.DO_NOT_TELEMARKET,mart.EMAIL_CHANGE_DATE,mart.EMAIL_MARKETING_CONSENT_INDICATOR,mart.EMAIL_OPT_DATE,mart.ESTATEMENT_CHANGE_DATE,mart.ESTATEMENT_INDICATOR,mart.FIRST_NAME,mart.FOREIGN_MAP_CODE,mart.INDICATOR,mart.LAST_4_DIGITS_OF_ACCOUNT_NUMBER,mart.LAST_MODIFIED,mart.LAST_NAME,mart.LAST_PAYMENT_DATE,mart.LAST_PURCHASE_DATE,mart.LAST_RETURN_DATE,mart.LOGO,mart.LOGO_CHANGE_DATE,mart.MARKETING_PROMO_FLAG,mart.MGN_ID,mart.MIDDLE_NAME,mart.MOBILE_PUSH_CONSENT_INDICATOR,mart.NEW_ACCOUNT_CLERK_NUMBER,mart.NUMBER_OF_CARDS_ISSUED,mart.OPEN_DATE,mart.PERSON_ID,mart.PRESCREEN_ID,mart.PREVIOUS_ACCOUNT_NUMBER,mart.PREVIOUS_CREDIT_TERM_NUMBER,mart.PROMOTABILITY_INDICATOR,mart.RECOURSE_INDICATOR,mart.RETURN_MAIL_INDICATOR,mart.SLANGUAGEINDICATOR,mart.SMS_MARKETING_CONSENT_INDICATOR,mart.SMS_SERVICE_CONSENT_INDICATOR,mart.SPAM_INDICATOR,mart.STATEMENT_SUBSCRIPTION_INDICATOR,mart.SUR_TITLE,mart.TRANSFERRED_FROM_ACCOUNT_NUMBER,mart.YTD_PURCHASE_AMOUNT,mart.EMAIL,mart.COMPLETE_NUMBER,mart.COMPLETE_NUMBER_1,mart.COMPLETE_NUMBER_2,mart.INDIVIDUAL_ID,mart.ADDRESS_LINE_1,mart.CITY_NAME,mart.STATE,mart.POSTAL_CODE,mart.POSTAL_CODE_EXTENSION,mart.BUSINESS_UNIT_ID,mart.INDIVIDUAL_KEY
FROM ulta_mart_customer.CREDIT_CARD_ACCOUNT_DIMENSION mart LEFT OUTER JOIN ulta_base_customer.CREDIT_CARD_ACCOUNT_DIMENSION stage 
ON mart.ACCOUNT_NUMBER = stage.ACCOUNT_NUMBER
where stage.ACCOUNT_NUMBER is null

--3. delete data from mart and take back up
bq cp ulta_mart_customer.CREDIT_CARD_ACCOUNT_DIMENSION ulta_mart_customer.CREDIT_CARD_ACCOUNT_DIMENSION_20180731
DELETE ulta_mart_customer.CREDIT_CARD_ACCOUNT_DIMENSION WHERE TRUE



--4. Populate mart table 

insert into ulta_mart_customer.CREDIT_CARD_ACCOUNT_DIMENSION (CREDIT_CARD_ACCOUNT_KEY,ACCEPTANCE_REFERRAL_CODE,ACCOUNT_INDICATOR_01,ACCOUNT_INDICATOR_02,ACCOUNT_INDICATOR_03,ACCOUNT_NUMBER,ACTIVATION_FLAG, ACTIVE_INACTIVE_INDICATOR,ADDRESS_CHANGE,ADOBE_ACTIVE_INACTIVE_INDICATOR,AMOUNT_OF_LAST_PAYMENT,AMOUNT_OF_LAST_PURCHASE,APPLICATION_NUMBER, APPLICATION_SOURCE_CODE,BALANCE_ALL_PLANS,BIRTH_DATE,CARD_EXPIRE_DATE,CARD_ISSUE_DATE,CARD_NUMBER,CLERK_NUMBER,CLOSED_DATE,COBRAND_EXPIRATION_DATE, CREATED_DATE,CREDIT_LIMIT,CREDIT_TERM_NUMBER,CREDIT_TERM_NUMBER_CARD_TYPE,CURRENT_OTB,CYCLE_NUMBER,CYCLE_UPDATE_DATE,DIVISION_NUMBER, DO_NOT_DIRECT_MAIL,DO_NOT_SELL_NAME,DO_NOT_STATEMENT_INSERT,DO_NOT_TELEMARKET,EMAIL_CHANGE_DATE,EMAIL_MARKETING_CONSENT_INDICATOR,EMAIL_OPT_DATE, ESTATEMENT_CHANGE_DATE,ESTATEMENT_INDICATOR,FIRST_NAME,FOREIGN_MAP_CODE,INDICATOR,LAST_4_DIGITS_OF_ACCOUNT_NUMBER,LAST_MODIFIED,LAST_NAME, LAST_PAYMENT_DATE,LAST_PURCHASE_DATE,LAST_RETURN_DATE,LOGO,LOGO_CHANGE_DATE,MARKETING_PROMO_FLAG,MGN_ID,MIDDLE_NAME,MOBILE_PUSH_CONSENT_INDICATOR, NEW_ACCOUNT_CLERK_NUMBER,NUMBER_OF_CARDS_ISSUED,OPEN_DATE,PERSON_ID,PRESCREEN_ID,PREVIOUS_ACCOUNT_NUMBER,PREVIOUS_CREDIT_TERM_NUMBER, PROMOTABILITY_INDICATOR,RECOURSE_INDICATOR,RETURN_MAIL_INDICATOR,SLANGUAGEINDICATOR,SMS_MARKETING_CONSENT_INDICATOR,SMS_SERVICE_CONSENT_INDICATOR, SPAM_INDICATOR,STATEMENT_SUBSCRIPTION_INDICATOR,SUR_TITLE,TRANSFERRED_FROM_ACCOUNT_NUMBER,YTD_PURCHASE_AMOUNT,EMAIL,COMPLETE_NUMBER,COMPLETE_NUMBER_1, COMPLETE_NUMBER_2,INDIVIDUAL_ID,ADDRESS_LINE_1,CITY_NAME,STATE,POSTAL_CODE,POSTAL_CODE_EXTENSION,BUSINESS_UNIT_ID,INDIVIDUAL_KEY)
select CREDIT_CARD_ACCOUNT_KEY,ACCEPTANCE_REFERRAL_CODE,ACCOUNT_INDICATOR_01,ACCOUNT_INDICATOR_02,ACCOUNT_INDICATOR_03,ACCOUNT_NUMBER,ACTIVATION_FLAG, ACTIVE_INACTIVE_INDICATOR,ADDRESS_CHANGE,ADOBE_ACTIVE_INACTIVE_INDICATOR,AMOUNT_OF_LAST_PAYMENT,AMOUNT_OF_LAST_PURCHASE,APPLICATION_NUMBER, APPLICATION_SOURCE_CODE,BALANCE_ALL_PLANS,BIRTH_DATE,CARD_EXPIRE_DATE,CARD_ISSUE_DATE,CARD_NUMBER,CLERK_NUMBER,CLOSED_DATE,COBRAND_EXPIRATION_DATE, CREATED_DATE,CREDIT_LIMIT,CREDIT_TERM_NUMBER,CREDIT_TERM_NUMBER_CARD_TYPE,CURRENT_OTB,CYCLE_NUMBER,CYCLE_UPDATE_DATE,DIVISION_NUMBER, DO_NOT_DIRECT_MAIL,DO_NOT_SELL_NAME,DO_NOT_STATEMENT_INSERT,DO_NOT_TELEMARKET,EMAIL_CHANGE_DATE,EMAIL_MARKETING_CONSENT_INDICATOR,EMAIL_OPT_DATE, ESTATEMENT_CHANGE_DATE,ESTATEMENT_INDICATOR,FIRST_NAME,FOREIGN_MAP_CODE,INDICATOR,LAST_4_DIGITS_OF_ACCOUNT_NUMBER,LAST_MODIFIED,LAST_NAME, LAST_PAYMENT_DATE,LAST_PURCHASE_DATE,LAST_RETURN_DATE,LOGO,LOGO_CHANGE_DATE,MARKETING_PROMO_FLAG,MGN_ID,MIDDLE_NAME,MOBILE_PUSH_CONSENT_INDICATOR, NEW_ACCOUNT_CLERK_NUMBER,NUMBER_OF_CARDS_ISSUED,OPEN_DATE,PERSON_ID,PRESCREEN_ID,PREVIOUS_ACCOUNT_NUMBER,PREVIOUS_CREDIT_TERM_NUMBER, PROMOTABILITY_INDICATOR,RECOURSE_INDICATOR,RETURN_MAIL_INDICATOR,SLANGUAGEINDICATOR,SMS_MARKETING_CONSENT_INDICATOR,SMS_SERVICE_CONSENT_INDICATOR, SPAM_INDICATOR,STATEMENT_SUBSCRIPTION_INDICATOR,SUR_TITLE,TRANSFERRED_FROM_ACCOUNT_NUMBER,YTD_PURCHASE_AMOUNT,EMAIL,COMPLETE_NUMBER,COMPLETE_NUMBER_1, COMPLETE_NUMBER_2,INDIVIDUAL_ID,ADDRESS_LINE_1,CITY_NAME,STATE,POSTAL_CODE,POSTAL_CODE_EXTENSION,BUSINESS_UNIT_ID,INDIVIDUAL_KEY
from ulta_base_customer.CREDIT_CARD_ACCOUNT_DIMENSION
UNION ALL
select CREDIT_CARD_ACCOUNT_KEY,ACCEPTANCE_REFERRAL_CODE,ACCOUNT_INDICATOR_01,ACCOUNT_INDICATOR_02,ACCOUNT_INDICATOR_03,ACCOUNT_NUMBER,ACTIVATION_FLAG, ACTIVE_INACTIVE_INDICATOR,ADDRESS_CHANGE,ADOBE_ACTIVE_INACTIVE_INDICATOR,AMOUNT_OF_LAST_PAYMENT,AMOUNT_OF_LAST_PURCHASE,APPLICATION_NUMBER, APPLICATION_SOURCE_CODE,BALANCE_ALL_PLANS,BIRTH_DATE,CARD_EXPIRE_DATE,CARD_ISSUE_DATE,CARD_NUMBER,CLERK_NUMBER,CLOSED_DATE,COBRAND_EXPIRATION_DATE, CREATED_DATE,CREDIT_LIMIT,CREDIT_TERM_NUMBER,CREDIT_TERM_NUMBER_CARD_TYPE,CURRENT_OTB,CYCLE_NUMBER,CYCLE_UPDATE_DATE,DIVISION_NUMBER, DO_NOT_DIRECT_MAIL,DO_NOT_SELL_NAME,DO_NOT_STATEMENT_INSERT,DO_NOT_TELEMARKET,EMAIL_CHANGE_DATE,EMAIL_MARKETING_CONSENT_INDICATOR,EMAIL_OPT_DATE, ESTATEMENT_CHANGE_DATE,ESTATEMENT_INDICATOR,FIRST_NAME,FOREIGN_MAP_CODE,INDICATOR,LAST_4_DIGITS_OF_ACCOUNT_NUMBER,LAST_MODIFIED,LAST_NAME, LAST_PAYMENT_DATE,LAST_PURCHASE_DATE,LAST_RETURN_DATE,LOGO,LOGO_CHANGE_DATE,MARKETING_PROMO_FLAG,MGN_ID,MIDDLE_NAME,MOBILE_PUSH_CONSENT_INDICATOR, NEW_ACCOUNT_CLERK_NUMBER,NUMBER_OF_CARDS_ISSUED,OPEN_DATE,PERSON_ID,PRESCREEN_ID,PREVIOUS_ACCOUNT_NUMBER,PREVIOUS_CREDIT_TERM_NUMBER, PROMOTABILITY_INDICATOR,RECOURSE_INDICATOR,RETURN_MAIL_INDICATOR,SLANGUAGEINDICATOR,SMS_MARKETING_CONSENT_INDICATOR,SMS_SERVICE_CONSENT_INDICATOR, SPAM_INDICATOR,STATEMENT_SUBSCRIPTION_INDICATOR,SUR_TITLE,TRANSFERRED_FROM_ACCOUNT_NUMBER,YTD_PURCHASE_AMOUNT,EMAIL,COMPLETE_NUMBER,COMPLETE_NUMBER_1, COMPLETE_NUMBER_2,INDIVIDUAL_ID,ADDRESS_LINE_1,CITY_NAME,STATE,POSTAL_CODE,POSTAL_CODE_EXTENSION,BUSINESS_UNIT_ID,INDIVIDUAL_KEY 
from ulta_base_customer.CREDIT_CARD_ACCOUNT_DIMENSION_UNCHANGED
