--DDL
bq mk -t ulta_base_date_time.DATE_DIMENSION DATE_KEY:INTEGER,BUSINESS_DAY_DATE:DATE,CALENDAR_YEAR:INTEGER,CALENDAR_QUARTER:INTEGER,CALENDAR_MONTH:INTEGER,CALENDAR_WEEK:INTEGER,CALENDAR_WEEK_DAY:INTEGER,CALENDAR_HOLIDAY_FLAG:INTEGER,CALENDAR_HOLIDAY:STRING,FISCAL_YEAR:INTEGER,FISCAL_QUARTER:INTEGER,FISCAL_PERIOD:INTEGER,FISCAL_WEEK:INTEGER,FISCAL_ALL:INTEGER


bq mk -t ulta_base_date_time.DATE_DIMENSION_UNCHANGED DATE_KEY:INTEGER,BUSINESS_DAY_DATE:DATE,CALENDAR_YEAR:INTEGER,CALENDAR_QUARTER:INTEGER,CALENDAR_MONTH:INTEGER,CALENDAR_WEEK:INTEGER,CALENDAR_WEEK_DAY:INTEGER,CALENDAR_HOLIDAY_FLAG:INTEGER,CALENDAR_HOLIDAY:STRING,FISCAL_YEAR:INTEGER,FISCAL_QUARTER:INTEGER,FISCAL_PERIOD:INTEGER,FISCAL_WEEK:INTEGER,FISCAL_ALL:INTEGER


bq mk -t ulta_mart_date_time.DATE_DIMENSION DATE_KEY:INTEGER,BUSINESS_DAY_DATE:DATE,CALENDAR_YEAR:INTEGER,CALENDAR_QUARTER:INTEGER,CALENDAR_MONTH:INTEGER,CALENDAR_WEEK:INTEGER,CALENDAR_WEEK_DAY:INTEGER,CALENDAR_HOLIDAY_FLAG:INTEGER,CALENDAR_HOLIDAY:STRING,FISCAL_YEAR:INTEGER,FISCAL_QUARTER:INTEGER,FISCAL_PERIOD:INTEGER,FISCAL_WEEK:INTEGER,FISCAL_ALL:INTEGER


--1. Step to insert in to stage table
DELETE ulta_base_date_time.DATE_DIMENSION WHERE TRUE;


INSERT INTO ulta_base_date_time.DATE_DIMENSION (DATE_KEY,BUSINESS_DAY_DATE,CALENDAR_YEAR,CALENDAR_QUARTER,CALENDAR_MONTH,CALENDAR_WEEK,CALENDAR_WEEK_DAY,CALENDAR_HOLIDAY_FLAG,CALENDAR_HOLIDAY,FISCAL_YEAR,FISCAL_QUARTER,FISCAL_PERIOD,FISCAL_WEEK,FISCAL_ALL)
select 
NULL as DATE_KEY -- will be populated from keys
,DW.BUSINESS_DAY_DATE AS BUSINESS_DAY_DATE
,DW.CALENDAR_YEAR AS CALENDAR_YEAR
,DW.CALENDAR_QUARTER AS CALENDAR_QUARTER
,DW.CALENDAR_MONTH as CALENDAR_MONTH
,DW.CALENDAR_WEEK as CALENDAR_WEEK
DW.CALENDAR_WEEK_DAY as CALENDAR_WEEK_DAY
,COALESCE(ABS(DW.WEEKDAY_FLAG-1),HC.HOLIDAY_FLAG) AS CALENDAR_HOLIDAY_FLAG
,HC.HOLIDAY_NAME as CALENDAR_HOLIDAY
,FW.PERIOD_YEAR as FISCAL_YEAR
,CASE
  WHEN FW.PERIOD IN ('1','2','3') THEN 1
  WHEN FW.PERIOD IN ('4','5','6') THEN 2
  WHEN FW.PERIOD IN ('7','8','9') THEN 3
  WHEN FW.PERIOD IN ('10','11','12') THEN 4
 END as FISCAL_QUARTER
,FW.PERIOD as FISCAL_PERIOD
,FW.WEEK_NUMBER as FISCAL_WEEK
,(IFNULL(FW.PERIOD_YEAR,0)*10000)+ (IFNULL(FW.PERIOD,0)*100) + (IFNULL(WEEK_NUMBER,0)) as FISCAL_ALL
from ulta_land.DW_DATE DW
LEFT OUTER JOIN ulta_land.HOLIDAY_CALENDAR HC
ON DW.BUSINESS_DAY_DATE = HC.HOLIDAY_DATE
LEFT OUTER JOIN ulta_land.FISCALWEEK FW
ON DW.BUSINESS_DAY_DATE=FW.DATE_;


--2. populate unchanged stage table
DELETE ulta_base_date_time.DATE_DIMENSION_UNCHANGED WHERE TRUE;

INSERT INTO ulta_base_date_time.DATE_DIMENSION_UNCHANGED ( DATE_KEY,BUSINESS_DAY_DATE,CALENDAR_YEAR,CALENDAR_QUARTER,CALENDAR_MONTH,CALENDAR_WEEK,CALENDAR_WEEK_DAY,CALENDAR_HOLIDAY_FLAG,CALENDAR_HOLIDAY,FISCAL_YEAR,FISCAL_QUARTER,FISCAL_PERIOD,FISCAL_WEEK,FISCAL_ALL )
SELECT  mart.DATE_KEY,mart.BUSINESS_DAY_DATE,mart.CALENDAR_YEAR,mart.CALENDAR_QUARTER,mart.CALENDAR_MONTH,mart.CALENDAR_WEEK,mart.CALENDAR_WEEK_DAY,mart.CALENDAR_HOLIDAY_FLAG,mart.CALENDAR_HOLIDAY,mart.FISCAL_YEAR,mart.FISCAL_QUARTER,mart.FISCAL_PERIOD,mart.FISCAL_WEEK,mart.FISCAL_ALL 
FROM ulta_mart_date_time.DATE_DIMENSION mart LEFT OUTER JOIN ulta_base_date_time.DATE_DIMENSION stage 
ON mart.BUSINESS_DAY_DATE = stage.BUSINESS_DAY_DATE
where stage.BUSINESS_DAY_DATE is null;


--3. delete data from mart and take back up
bq cp ulta_mart_date_time.DATE_DIMENSION ULTA_MART.DATE_DIMENSION_20180726
DELETE ulta_mart_date_time.DATE_DIMENSION WHERE TRUE;


--4. Populate mart table 

INSERT INTO ulta_mart_date_time.DATE_DIMENSION (DATE_KEY,BUSINESS_DAY_DATE,CALENDAR_YEAR,CALENDAR_QUARTER,CALENDAR_MONTH,CALENDAR_WEEK,CALENDAR_WEEK_DAY,CALENDAR_HOLIDAY_FLAG,CALENDAR_HOLIDAY,FISCAL_YEAR,FISCAL_QUARTER,FISCAL_PERIOD,FISCAL_WEEK,FISCAL_ALL)
select DATE_KEY,BUSINESS_DAY_DATE,CALENDAR_YEAR,CALENDAR_QUARTER,CALENDAR_MONTH,CALENDAR_WEEK,CALENDAR_WEEK_DAY,CALENDAR_HOLIDAY_FLAG,CALENDAR_HOLIDAY,FISCAL_YEAR,FISCAL_QUARTER,FISCAL_PERIOD,FISCAL_WEEK,FISCAL_ALL from ulta_base_date_time.DATE_DIMENSION
UNION ALL
select DATE_KEY,BUSINESS_DAY_DATE,CALENDAR_YEAR,CALENDAR_QUARTER,CALENDAR_MONTH,CALENDAR_WEEK,CALENDAR_WEEK_DAY,CALENDAR_HOLIDAY_FLAG,CALENDAR_HOLIDAY,FISCAL_YEAR,FISCAL_QUARTER,FISCAL_PERIOD,FISCAL_WEEK,FISCAL_ALL from ulta_base_date_time.DATE_DIMENSION_UNCHANGED;

