--DDL
bq mk -t ulta_work.INDIVIDUAL_DIMENSION INDIVIDUAL_KEY:INTEGER,INDIVIDUAL_ID:STRING,FIRST_NAME:STRING,LAST_NAME:STRING,SALUTATION:STRING,PRIMARY_POSTAL_TOUCHPOINT_KEY:INTEGER,PRIMARY_EMAIL_TOUCHPOINT_KEY:INTEGER,PRIMARY_COMPLETE_PHONE_NUMBER:STRING,MOBILE_COMPLETE_PHONE_NUMBER:STRING,BIRTH_DATE:DATE,DECEASED:STRING,DELETED_FLAG:BOOLEAN,DO_NOT_MAIL:STRING,GENDER:STRING,LAST_NAME_SECONDARY:STRING,LAST_PURCHASE_DATE:DATE,MAIL_OPT_IN:STRING,SIGN_UP_DATE:DATE,CARD_NUMBER:STRING,PRIMARY_CARD_TOUCHPOINT_KEY:INTEGER,EMAIL_OPTDOWN_SURVEYS:BOOLEAN,EMAIL_OPTDOWN_SURVEYS_DATE:DATE,EMAIL_OPTDOWN_PROMO:BOOLEAN,EMAIL_OPTDOWN_PROMO_DATE:DATE,EMAIL_OPTDOWN_SALON:BOOLEAN,EMAIL_OPTDOWN_SALON_DATE:DATE,EMAIL_OPTDOWN_REWARDS:BOOLEAN,EMAIL_OPTDOWN_REWARDS_DATE:DATE,GENDER_SOURCE:STRING,FINAL_GENDER:STRING,PRIMARY_INTERNATIONAL_ADDRESS:STRING,SECONDARY_INTERNATIONAL_ADDRESS:STRING,EMAIL_ACQUISITION_OPT_OUT:STRING

bq mk -t ulta_work.INDIVIDUAL_DIMENSION_UNCHANGED INDIVIDUAL_KEY:INTEGER,INDIVIDUAL_ID:STRING,FIRST_NAME:STRING,LAST_NAME:STRING,SALUTATION:STRING,PRIMARY_POSTAL_TOUCHPOINT_KEY:INTEGER,PRIMARY_EMAIL_TOUCHPOINT_KEY:INTEGER,PRIMARY_COMPLETE_PHONE_NUMBER:STRING,MOBILE_COMPLETE_PHONE_NUMBER:STRING,BIRTH_DATE:DATE,DECEASED:STRING,DELETED_FLAG:BOOLEAN,DO_NOT_MAIL:STRING,GENDER:STRING,LAST_NAME_SECONDARY:STRING,LAST_PURCHASE_DATE:DATE,MAIL_OPT_IN:STRING,SIGN_UP_DATE:DATE,CARD_NUMBER:STRING,PRIMARY_CARD_TOUCHPOINT_KEY:INTEGER,EMAIL_OPTDOWN_SURVEYS:BOOLEAN,EMAIL_OPTDOWN_SURVEYS_DATE:DATE,EMAIL_OPTDOWN_PROMO:BOOLEAN,EMAIL_OPTDOWN_PROMO_DATE:DATE,EMAIL_OPTDOWN_SALON:BOOLEAN,EMAIL_OPTDOWN_SALON_DATE:DATE,EMAIL_OPTDOWN_REWARDS:BOOLEAN,EMAIL_OPTDOWN_REWARDS_DATE:DATE,GENDER_SOURCE:STRING,FINAL_GENDER:STRING,PRIMARY_INTERNATIONAL_ADDRESS:STRING,SECONDARY_INTERNATIONAL_ADDRESS:STRING,EMAIL_ACQUISITION_OPT_OUT:STRING

bq mk -t ulta_mart.INDIVIDUAL_DIMENSION INDIVIDUAL_KEY:INTEGER,INDIVIDUAL_ID:STRING,FIRST_NAME:STRING,LAST_NAME:STRING,SALUTATION:STRING,PRIMARY_POSTAL_TOUCHPOINT_KEY:INTEGER,PRIMARY_EMAIL_TOUCHPOINT_KEY:INTEGER,PRIMARY_COMPLETE_PHONE_NUMBER:STRING,MOBILE_COMPLETE_PHONE_NUMBER:STRING,BIRTH_DATE:DATE,DECEASED:STRING,DELETED_FLAG:BOOLEAN,DO_NOT_MAIL:STRING,GENDER:STRING,LAST_NAME_SECONDARY:STRING,LAST_PURCHASE_DATE:DATE,MAIL_OPT_IN:STRING,SIGN_UP_DATE:DATE,CARD_NUMBER:STRING,PRIMARY_CARD_TOUCHPOINT_KEY:INTEGER,EMAIL_OPTDOWN_SURVEYS:BOOLEAN,EMAIL_OPTDOWN_SURVEYS_DATE:DATE,EMAIL_OPTDOWN_PROMO:BOOLEAN,EMAIL_OPTDOWN_PROMO_DATE:DATE,EMAIL_OPTDOWN_SALON:BOOLEAN,EMAIL_OPTDOWN_SALON_DATE:DATE,EMAIL_OPTDOWN_REWARDS:BOOLEAN,EMAIL_OPTDOWN_REWARDS_DATE:DATE,GENDER_SOURCE:STRING,FINAL_GENDER:STRING,PRIMARY_INTERNATIONAL_ADDRESS:STRING,SECONDARY_INTERNATIONAL_ADDRESS:STRING,EMAIL_ACQUISITION_OPT_OUT:STRING

bq mk -t ulta_work.INDIVIDUAL_DIMENSION_UPDATED INDIVIDUAL_KEY:INTEGER,INDIVIDUAL_ID:STRING,FIRST_NAME:STRING,LAST_NAME:STRING,SALUTATION:STRING,PRIMARY_POSTAL_TOUCHPOINT_KEY:INTEGER,PRIMARY_EMAIL_TOUCHPOINT_KEY:INTEGER,PRIMARY_COMPLETE_PHONE_NUMBER:STRING,MOBILE_COMPLETE_PHONE_NUMBER:STRING,BIRTH_DATE:DATE,DECEASED:STRING,DELETED_FLAG:BOOLEAN,DO_NOT_MAIL:STRING,GENDER:STRING,LAST_NAME_SECONDARY:STRING,LAST_PURCHASE_DATE:DATE,MAIL_OPT_IN:STRING,SIGN_UP_DATE:DATE,CARD_NUMBER:STRING,PRIMARY_CARD_TOUCHPOINT_KEY:INTEGER,EMAIL_OPTDOWN_SURVEYS:BOOLEAN,EMAIL_OPTDOWN_SURVEYS_DATE:DATE,EMAIL_OPTDOWN_PROMO:BOOLEAN,EMAIL_OPTDOWN_PROMO_DATE:DATE,EMAIL_OPTDOWN_SALON:BOOLEAN,EMAIL_OPTDOWN_SALON_DATE:DATE,EMAIL_OPTDOWN_REWARDS:BOOLEAN,EMAIL_OPTDOWN_REWARDS_DATE:DATE,GENDER_SOURCE:STRING,FINAL_GENDER:STRING,PRIMARY_INTERNATIONAL_ADDRESS:STRING,SECONDARY_INTERNATIONAL_ADDRESS:STRING,EMAIL_ACQUISITION_OPT_OUT:STRING

bq mk -t ulta_work.DRIVER_EMAIL_OPTDOWN RECIPIENT_ID:INTEGER,EMAIL_OPTDOWN_PROMO:BOOLEAN,EMAIL_OPTDOWN_PROMO_DATE:DATE,EMAIL_OPTDOWN_REWARDS:BOOLEAN,EMAIL_OPTDOWN_REWARDS_DATE:DATE,EMAIL_OPTDOWN_SALON:BOOLEAN,EMAIL_OPTDOWN_SALON_DATE:DATE,EMAIL_OPTDOWN_SURVEYS:BOOLEAN,EMAIL_OPTDOWN_SURVEYS_DATE:DATE

bq mk -t ulta_work.EMAILOPTDOWNRANKED IOPTIN:BOOLEAN,IOPTINTYPEID:INTEGER,TSLASTMODIFIED:TIMESTAMP,IRECIPIENTID:INTEGER

bq mk -t ulta_work.SURVEYDATA_RANKED IGENDER:STRING,IRECIPIENTID:INTEGER

bq mk -t ulta_work.PREFERENCE_RANKED SPREFERENCEVALUE:STRING,IRECIPIENTID:INTEGER

bq mk -t ulta_work.RECIPIENTS_ID_SOURCES RECIPIENT_ID:STRING,LOAD_DATE:TIMESTAMP

bq mk -t ulta_work.DRIVER_TABLE_IND_DIM INDIVIDUAL_ID:STRING,PRIMARY_COMPLETE_PHONE_NUMBER:STRING,MOBILE_COMPLETE_PHONE_NUMBER:STRING

--1. Populate Intermediate EMAILOPTDOWN data:
DELETE ulta_work.EMAILOPTDOWNRANKED WHERE TRUE;
DELETE ulta_work.SURVEYDATA_RANKED WHERE TRUE;
DELETE ulta_work.PREFERENCE_RANKED WHERE TRUE;
DELETE ulta_work.DRIVER_EMAIL_OPTDOWN WHERE TRUE;
DELETE ulta_work.DRIVER_TABLE_IND_DIM WHERE TRUE;
--DELETE ulta_work.RECIPIENTS_ID_SOURCES WHERE TRUE;  -- Need to decide whether to truncate or append.

INSERT INTO ulta_work.EMAILOPTDOWNRANKED(IOPTIN ,IOPTINTYPEID,TSLASTMODIFIED ,IRECIPIENTID)
 select IOPTIN ,IOPTINTYPEID,TSLASTMODIFIED ,IRECIPIENTID from  (
 select IOPTIN,IOPTINTYPEID,IRECIPIENTID,TSLASTMODIFIED,ROW_NUMBER() over (partition by IOPTINTYPEID,IRECIPIENTID order by TSLASTMODIFIED desc) as RANKED FROM ulta_incoming.EMAILOPTDOWN WHERE IRECIPIENTID <> 0
 ) RANKED where RANKED.RANKED = 1;
 
 INSERT INTO ulta_work.SURVEYDATA_RANKED(IGENDER ,IRECIPIENTID)
 select cast(IGENDER as STRING) AS IGENDER ,IRECIPIENTID from  (
 select IGENDER ,IRECIPIENTID,ROW_NUMBER() over (partition by IRECIPIENTID order by ISURVEYDATAID desc) as RANKED FROM ulta_incoming.SURVEYDATA WHERE IRECIPIENTID <> 0
 ) RANKED where RANKED.RANKED = 1;
 
 INSERT INTO ulta_work.PREFERENCE_RANKED(SPREFERENCEVALUE,IRECIPIENTID)
 select SPREFERENCEVALUE,IRECIPIENTID from  (
 select SPREFERENCEVALUE,IRECIPIENTID,ROW_NUMBER() over (partition by IRECIPIENTID order by IPREFERENCEID desc) as RANKED FROM ulta_incoming.PREFERENCE WHERE IRECIPIENTID <> 0 AND SPREFERENCENAME = 'gender'
 ) RANKED where RANKED.RANKED = 1;
 
INSERT INTO ulta_work.DRIVER_EMAIL_OPTDOWN(RECIPIENT_ID,EMAIL_OPTDOWN_PROMO,EMAIL_OPTDOWN_PROMO_DATE,EMAIL_OPTDOWN_REWARDS,EMAIL_OPTDOWN_REWARDS_DATE,EMAIL_OPTDOWN_SALON, EMAIL_OPTDOWN_SALON_DATE,EMAIL_OPTDOWN_SURVEYS,EMAIL_OPTDOWN_SURVEYS_DATE)
select RECIPIENT_ID,EMAIL_OPTDOWN_PROMO,cast(EMAIL_OPTDOWN_PROMO_DATE as DATE) AS EMAIL_OPTDOWN_PROMO_DATE,EMAIL_OPTDOWN_REWARDS,cast(EMAIL_OPTDOWN_REWARDS_DATE as DATE) AS  EMAIL_OPTDOWN_REWARDS_DATE,EMAIL_OPTDOWN_SALON, cast(EMAIL_OPTDOWN_SALON_DATE AS DATE) AS EMAIL_OPTDOWN_SALON_DATE,EMAIL_OPTDOWN_SURVEYS,cast(EMAIL_OPTDOWN_SURVEYS_DATE AS DATE) AS EMAIL_OPTDOWN_SURVEYS_DATE
from 
ulta_incoming.RECIPIENTS r
LEFT OUTER JOIN
(select IOPTIN as EMAIL_OPTDOWN_PROMO,TSLASTMODIFIED as EMAIL_OPTDOWN_PROMO_DATE,IRECIPIENTID FROM ulta_work.EMAILOPTDOWNRANKED where IOPTINTYPEID = 12) E12
ON r.RECIPIENT_ID = E12.IRECIPIENTID
LEFT OUTER JOIN
(select IOPTIN as EMAIL_OPTDOWN_REWARDS,TSLASTMODIFIED as EMAIL_OPTDOWN_REWARDS_DATE,IRECIPIENTID FROM ulta_work.EMAILOPTDOWNRANKED where IOPTINTYPEID = 13) E13
ON r.RECIPIENT_ID = E13.IRECIPIENTID
LEFT OUTER JOIN
(select IOPTIN as EMAIL_OPTDOWN_SALON,TSLASTMODIFIED as EMAIL_OPTDOWN_SALON_DATE,IRECIPIENTID FROM ulta_work.EMAILOPTDOWNRANKED where IOPTINTYPEID = 14) E14
ON r.RECIPIENT_ID = E14.IRECIPIENTID
LEFT OUTER JOIN
(select IOPTIN as EMAIL_OPTDOWN_SURVEYS,TSLASTMODIFIED as EMAIL_OPTDOWN_SURVEYS_DATE,IRECIPIENTID FROM ulta_work.EMAILOPTDOWNRANKED where IOPTINTYPEID = 15) E15
ON r.RECIPIENT_ID = E15.IRECIPIENTID;


--2. LOAD DRIVER TABLE
INSERT INTO ulta_work.DRIVER_TABLE_IND_DIM(INDIVIDUAL_ID,PRIMARY_COMPLETE_PHONE_NUMBER,MOBILE_COMPLETE_PHONE_NUMBER)
SELECT CAST(REC.RECIPIENT_ID AS STRING) AS INDIVIDUAL_ID
,COALESCE(PHONE.SPHONE,SURVEYDATA.SPHONENUMBER,CC.SHOMEPHONENUMBER,CC.SMOBILEPHONENUMBER,CC.SEMPLOYEEPHONENUMBER) AS PRIMARY_COMPLETE_PHONE_NUMBER
,COALESCE(PHONE.SPHONE,SURVEYDATA.SPHONENUMBER,CC.SHOMEPHONENUMBER,CC.SMOBILEPHONENUMBER,CC.SEMPLOYEEPHONENUMBER) AS MOBILE_COMPLETE_PHONE_NUMBER
FROM ulta_incoming.RECIPIENTS REC
LEFT OUTER JOIN (select IRECIPIENTID,SPHONE from  (
 select IRECIPIENTID,SPHONE,ROW_NUMBER() over (partition by IRECIPIENTID order by IPHONEID asc) as RANKED FROM ulta_incoming.PHONENUMBER WHERE IRECIPIENTID <> 0
 ) RANKED where RANKED.RANKED = 1) PHONE
ON REC.RECIPIENT_ID = PHONE.IRECIPIENTID
LEFT OUTER JOIN (select IRECIPIENTID, SPHONENUMBER from  (
 select IRECIPIENTID, SPHONENUMBER,ROW_NUMBER() over (partition by IRECIPIENTID order by ISURVEYDATAID desc) as RANKED FROM ulta_incoming.SURVEYDATA WHERE IRECIPIENTID <> 0
 ) RANKED where RANKED.RANKED = 1) SURVEYDATA
ON REC.RECIPIENT_ID = SURVEYDATA.IRECIPIENTID
LEFT OUTER JOIN (select IRECIPIENTID,SHOMEPHONENUMBER,SMOBILEPHONENUMBER,SEMPLOYEEPHONENUMBER from  (
 select IRECIPIENTID,SHOMEPHONENUMBER,SMOBILEPHONENUMBER,SEMPLOYEEPHONENUMBER,ROW_NUMBER() over (partition by IRECIPIENTID order by TSLASTMODIFIED desc) as RANKED FROM ulta_incoming.CREDITCARDCUSTOMER WHERE IRECIPIENTID <> 0
 ) RANKED where RANKED.RANKED = 1) CC
ON REC.RECIPIENT_ID = CC.IRECIPIENTID
GROUP BY INDIVIDUAL_ID,PRIMARY_COMPLETE_PHONE_NUMBER,MOBILE_COMPLETE_PHONE_NUMBER;


--2. Step to insert in to stage table
DELETE ulta_work.INDIVIDUAL_DIMENSION WHERE TRUE;

INSERT INTO ulta_work.INDIVIDUAL_DIMENSION (INDIVIDUAL_KEY,INDIVIDUAL_ID,FIRST_NAME,LAST_NAME,SALUTATION,BIRTH_DATE,DECEASED,DO_NOT_MAIL,GENDER,LAST_NAME_SECONDARY,LAST_PURCHASE_DATE,MAIL_OPT_IN,SIGN_UP_DATE,CARD_NUMBER,PRIMARY_INTERNATIONAL_ADDRESS,SECONDARY_INTERNATIONAL_ADDRESS,EMAIL_ACQUISITION_OPT_OUT,PRIMARY_POSTAL_TOUCHPOINT_KEY,PRIMARY_EMAIL_TOUCHPOINT_KEY,PRIMARY_COMPLETE_PHONE_NUMBER,MOBILE_COMPLETE_PHONE_NUMBER,PRIMARY_CARD_TOUCHPOINT_KEY,GENDER_SOURCE,FINAL_GENDER,DELETED_FLAG,EMAIL_OPTDOWN_SURVEYS,EMAIL_OPTDOWN_SURVEYS_DATE,EMAIL_OPTDOWN_PROMO,EMAIL_OPTDOWN_PROMO_DATE,EMAIL_OPTDOWN_SALON,EMAIL_OPTDOWN_SALON_DATE,EMAIL_OPTDOWN_REWARDS,EMAIL_OPTDOWN_REWARDS_DATE)
SELECT 
NULL AS INDIVIDUAL_KEY, --will be populated from keys
cast(RECIPIENTS.RECIPIENT_ID as string) AS INDIVIDUAL_ID,
RECIPIENTS.FIRST_NAME AS FIRST_NAME,
RECIPIENTS.LAST_NAME AS LAST_NAME,
RECIPIENTS.TITLE AS SALUTATION,
CAST(SUBSTR(CASE WHEN RECIPIENTS.BIRTH_DATE = '' THEN NULL ELSE RECIPIENTS.BIRTH_DATE END,1,10) AS DATE) AS BIRTH_DATE,
RECIPIENTS.DECEASED AS DECEASED,
RECIPIENTS.DO_NOT_MAIL AS DO_NOT_MAIL,
RECIPIENTS.GENDER AS GENDER,
RECIPIENTS.LAST_NAME_SECONDARY AS LAST_NAME_SECONDARY,
CAST(SUBSTR(CASE WHEN RECIPIENTS.LAST_PURCHASE_DATE = '' THEN NULL ELSE RECIPIENTS.LAST_PURCHASE_DATE END,1,10) AS DATE) AS LAST_PURCHASE_DATE,
RECIPIENTS.MAIL_OPT_IN AS MAIL_OPT_IN,
cast(SUBSTR(CASE WHEN RECIPIENTS.SIGN_UP_DATE = '' THEN NULL ELSE RECIPIENTS.SIGN_UP_DATE END,1,10) AS DATE) AS SIGN_UP_DATE,
RECIPIENTS.CARD_NUMBER as CARD_NUMBER, -- as per discussion with vinod decided tables loyalty acct, online acct, salon cust
RECIPIENTS.PRIMARY_INTERNATIONAL_ADDRESS AS PRIMARY_INTERNATIONAL_ADDRESS,
RECIPIENTS.SECONDARY_INTERNATIONAL_ADDRESS AS SECONDARY_INTERNATIONAL_ADDRESS,
RECIPIENTS.EMAIL_ACQUISITION_OPT_OUT AS EMAIL_ACQUISITION_OPT_OUT,
NULL AS PRIMARY_POSTAL_TOUCHPOINT_KEY, --will be populated from keys
NULL AS PRIMARY_EMAIL_TOUCHPOINT_KEY, --will be populated from keys
DRIVER_IND.PRIMARY_COMPLETE_PHONE_NUMBER AS PRIMARY_COMPLETE_PHONE_NUMBER,
DRIVER_IND.MOBILE_COMPLETE_PHONE_NUMBER AS MOBILE_COMPLETE_PHONE_NUMBER,
NULL AS PRIMARY_CARD_TOUCHPOINT_KEY, --will be populated from keys
CASE
WHEN SURVEY.IGENDER in ('1','2') THEN 'Surv'
WHEN PREF.SPREFERENCEVALUE IS NOT NULL THEN 'Pref'
WHEN NGS.ASSOCIATION_SCORE > 0 OR NGS.ASSOCIATION_SCORE < 0 THEN 'Ulta'
WHEN EI.GENDER_CODE_PERSON_1_DSC IS NOT NULL THEN 'Eps'
WHEN RECIPIENTS.GENDER IS NOT NULL THEN 'LPS'
END AS GENDER_SOURCE,
CASE
WHEN SURVEY.IGENDER = '1' THEN 'M'
WHEN SURVEY.IGENDER = '2' THEN 'F'
WHEN PREF.SPREFERENCEVALUE IS NOT NULL AND UPPER(TRIM(PREF.SPREFERENCEVALUE)) = 'MALE' THEN 'M'
WHEN PREF.SPREFERENCEVALUE IS NOT NULL AND UPPER(TRIM(PREF.SPREFERENCEVALUE)) = 'FEMALE' THEN 'F'
WHEN NGS.ASSOCIATION_SCORE > 0 THEN 'M'
WHEN NGS.ASSOCIATION_SCORE < 0 THEN 'F'
WHEN EI.GENDER_CODE_PERSON_1_DSC IS NOT NULL AND UPPER(TRIM(EI.GENDER_CODE_PERSON_1_DSC)) = 'MALE' THEN 'M'
WHEN EI.GENDER_CODE_PERSON_1_DSC IS NOT NULL AND UPPER(TRIM(EI.GENDER_CODE_PERSON_1_DSC)) = 'FEMALE' THEN 'F'
WHEN RECIPIENTS.GENDER IS NOT NULL THEN RECIPIENTS.GENDER
END AS FINAL_GENDER,
FALSE AS DELETED_FLAG,
DRIVER.EMAIL_OPTDOWN_SURVEYS AS EMAIL_OPTDOWN_SURVEYS,
DRIVER.EMAIL_OPTDOWN_SURVEYS_DATE AS EMAIL_OPTDOWN_SURVEYS_DATE,
DRIVER.EMAIL_OPTDOWN_PROMO AS EMAIL_OPTDOWN_PROMO,
DRIVER.EMAIL_OPTDOWN_PROMO_DATE AS EMAIL_OPTDOWN_PROMO_DATE,
DRIVER.EMAIL_OPTDOWN_SALON AS EMAIL_OPTDOWN_SALON,
DRIVER.EMAIL_OPTDOWN_SALON_DATE AS EMAIL_OPTDOWN_SALON_DATE,
DRIVER.EMAIL_OPTDOWN_REWARDS AS EMAIL_OPTDOWN_REWARDS,
DRIVER.EMAIL_OPTDOWN_REWARDS_DATE AS EMAIL_OPTDOWN_REWARDS_DATE
FROM ulta_incoming.RECIPIENTS RECIPIENTS 
LEFT OUTER JOIN ulta_work.DRIVER_EMAIL_OPTDOWN DRIVER
ON RECIPIENTS.RECIPIENT_ID = DRIVER.RECIPIENT_ID
LEFT OUTER JOIN ulta_incoming.RECIPIENTS_DEL RECIPIENTS_DEL
ON RECIPIENTS.RECIPIENT_ID = RECIPIENTS_DEL.RECIPIENT_ID
LEFT OUTER JOIN ulta_work.DRIVER_TABLE_IND_DIM DRIVER_IND
ON CAST(RECIPIENTS.RECIPIENT_ID AS STRING) = DRIVER_IND.INDIVIDUAL_ID
LEFT OUTER JOIN ulta_work.SURVEYDATA_RANKED SURVEY
ON RECIPIENTS.RECIPIENT_ID = SURVEY.IRECIPIENTID
LEFT OUTER JOIN ulta_work.PREFERENCE_RANKED PREF
ON RECIPIENTS.RECIPIENT_ID = PREF.IRECIPIENTID
LEFT OUTER JOIN ulta_incoming.NAME_GENDER_SCORES NGS
ON UPPER(TRIM(RECIPIENTS.FIRST_NAME)) = UPPER(TRIM(NGS.FIRST_NAME))
LEFT OUTER JOIN ulta_mart.EPSILON_INDIVIDUAL EI
ON RECIPIENTS.RECIPIENT_ID = EI.INDIVIDUAL_ID;


--2. populate unchanged stage table
DELETE ulta_work.INDIVIDUAL_DIMENSION_UNCHANGED WHERE TRUE;

INSERT INTO ulta_work.INDIVIDUAL_DIMENSION_UNCHANGED (INDIVIDUAL_KEY,INDIVIDUAL_ID,FIRST_NAME,LAST_NAME,SALUTATION,BIRTH_DATE,DECEASED,DO_NOT_MAIL,GENDER,LAST_NAME_SECONDARY,LAST_PURCHASE_DATE,MAIL_OPT_IN,SIGN_UP_DATE,CARD_NUMBER,PRIMARY_INTERNATIONAL_ADDRESS,SECONDARY_INTERNATIONAL_ADDRESS,EMAIL_ACQUISITION_OPT_OUT,PRIMARY_POSTAL_TOUCHPOINT_KEY,PRIMARY_EMAIL_TOUCHPOINT_KEY,PRIMARY_COMPLETE_PHONE_NUMBER,MOBILE_COMPLETE_PHONE_NUMBER,PRIMARY_CARD_TOUCHPOINT_KEY,GENDER_SOURCE,FINAL_GENDER,DELETED_FLAG,EMAIL_OPTDOWN_SURVEYS,EMAIL_OPTDOWN_SURVEYS_DATE,EMAIL_OPTDOWN_PROMO,EMAIL_OPTDOWN_PROMO_DATE,EMAIL_OPTDOWN_SALON,EMAIL_OPTDOWN_SALON_DATE,EMAIL_OPTDOWN_REWARDS,EMAIL_OPTDOWN_REWARDS_DATE)
SELECT mart.INDIVIDUAL_KEY,mart.INDIVIDUAL_ID,mart.FIRST_NAME,mart.LAST_NAME,mart.SALUTATION,mart.BIRTH_DATE,mart.DECEASED,mart.DO_NOT_MAIL,mart.GENDER,mart.LAST_NAME_SECONDARY,mart.LAST_PURCHASE_DATE,mart.MAIL_OPT_IN,mart.SIGN_UP_DATE,mart.CARD_NUMBER,mart.PRIMARY_INTERNATIONAL_ADDRESS,mart.SECONDARY_INTERNATIONAL_ADDRESS,mart.EMAIL_ACQUISITION_OPT_OUT,mart.PRIMARY_POSTAL_TOUCHPOINT_KEY,mart.PRIMARY_EMAIL_TOUCHPOINT_KEY,mart.PRIMARY_COMPLETE_PHONE_NUMBER,mart.MOBILE_COMPLETE_PHONE_NUMBER,mart.PRIMARY_CARD_TOUCHPOINT_KEY,mart.GENDER_SOURCE,mart.FINAL_GENDER,mart.DELETED_FLAG,mart.EMAIL_OPTDOWN_SURVEYS,mart.EMAIL_OPTDOWN_SURVEYS_DATE,mart.EMAIL_OPTDOWN_PROMO,mart.EMAIL_OPTDOWN_PROMO_DATE,mart.EMAIL_OPTDOWN_SALON,mart.EMAIL_OPTDOWN_SALON_DATE,mart.EMAIL_OPTDOWN_REWARDS,mart.EMAIL_OPTDOWN_REWARDS_DATE
FROM ulta_mart.INDIVIDUAL_DIMENSION mart LEFT OUTER JOIN ulta_work.INDIVIDUAL_DIMENSION stage 
ON mart.INDIVIDUAL_ID = stage.INDIVIDUAL_ID
where stage.INDIVIDUAL_ID is null;


--2. populate updated stage table
DELETE ulta_work.INDIVIDUAL_DIMENSION_UPDATED WHERE TRUE;

INSERT INTO ulta_work.INDIVIDUAL_DIMENSION_UPDATED (INDIVIDUAL_KEY,INDIVIDUAL_ID,FIRST_NAME,LAST_NAME,SALUTATION,BIRTH_DATE,DECEASED,DO_NOT_MAIL,GENDER,LAST_NAME_SECONDARY,LAST_PURCHASE_DATE,MAIL_OPT_IN,SIGN_UP_DATE,CARD_NUMBER,PRIMARY_INTERNATIONAL_ADDRESS,SECONDARY_INTERNATIONAL_ADDRESS,EMAIL_ACQUISITION_OPT_OUT,PRIMARY_POSTAL_TOUCHPOINT_KEY,PRIMARY_EMAIL_TOUCHPOINT_KEY,PRIMARY_COMPLETE_PHONE_NUMBER,MOBILE_COMPLETE_PHONE_NUMBER,PRIMARY_CARD_TOUCHPOINT_KEY,GENDER_SOURCE,FINAL_GENDER,DELETED_FLAG,EMAIL_OPTDOWN_SURVEYS,EMAIL_OPTDOWN_SURVEYS_DATE,EMAIL_OPTDOWN_PROMO,EMAIL_OPTDOWN_PROMO_DATE,EMAIL_OPTDOWN_SALON,EMAIL_OPTDOWN_SALON_DATE,EMAIL_OPTDOWN_REWARDS,EMAIL_OPTDOWN_REWARDS_DATE)
SELECT mart.INDIVIDUAL_KEY,stage.INDIVIDUAL_ID,stage.FIRST_NAME,stage.LAST_NAME,stage.SALUTATION,stage.BIRTH_DATE,stage.DECEASED,stage.DO_NOT_MAIL,stage.GENDER,stage.LAST_NAME_SECONDARY,stage.LAST_PURCHASE_DATE,stage.MAIL_OPT_IN,stage.SIGN_UP_DATE,stage.CARD_NUMBER,stage.PRIMARY_INTERNATIONAL_ADDRESS,stage.SECONDARY_INTERNATIONAL_ADDRESS,stage.EMAIL_ACQUISITION_OPT_OUT,stage.PRIMARY_POSTAL_TOUCHPOINT_KEY,stage.PRIMARY_EMAIL_TOUCHPOINT_KEY,stage.PRIMARY_COMPLETE_PHONE_NUMBER,stage.MOBILE_COMPLETE_PHONE_NUMBER,stage.PRIMARY_CARD_TOUCHPOINT_KEY,stage.GENDER_SOURCE,stage.FINAL_GENDER,stage.DELETED_FLAG,stage.EMAIL_OPTDOWN_SURVEYS,stage.EMAIL_OPTDOWN_SURVEYS_DATE,stage.EMAIL_OPTDOWN_PROMO,stage.EMAIL_OPTDOWN_PROMO_DATE,stage.EMAIL_OPTDOWN_SALON,stage.EMAIL_OPTDOWN_SALON_DATE,stage.EMAIL_OPTDOWN_REWARDS,stage.EMAIL_OPTDOWN_REWARDS_DATE
FROM ulta_mart.INDIVIDUAL_DIMENSION mart INNER JOIN ulta_work.INDIVIDUAL_DIMENSION stage 
ON mart.INDIVIDUAL_ID = stage.INDIVIDUAL_ID;

--3. delete data from mart and take back up
bq cp ulta_mart.INDIVIDUAL_DIMENSION ulta_mart.INDIVIDUAL_DIMENSION_20180726
DELETE ulta_mart.INDIVIDUAL_DIMENSION WHERE TRUE;


--4. Populate mart table 
INSERT INTO ulta_mart.INDIVIDUAL_DIMENSION (INDIVIDUAL_KEY,INDIVIDUAL_ID,FIRST_NAME,LAST_NAME,SALUTATION,BIRTH_DATE,DECEASED,DO_NOT_MAIL,GENDER,LAST_NAME_SECONDARY,LAST_PURCHASE_DATE,MAIL_OPT_IN,SIGN_UP_DATE,CARD_NUMBER,PRIMARY_INTERNATIONAL_ADDRESS,SECONDARY_INTERNATIONAL_ADDRESS,EMAIL_ACQUISITION_OPT_OUT,PRIMARY_POSTAL_TOUCHPOINT_KEY,PRIMARY_EMAIL_TOUCHPOINT_KEY,PRIMARY_COMPLETE_PHONE_NUMBER,MOBILE_COMPLETE_PHONE_NUMBER,PRIMARY_CARD_TOUCHPOINT_KEY,GENDER_SOURCE,FINAL_GENDER,DELETED_FLAG,EMAIL_OPTDOWN_SURVEYS,EMAIL_OPTDOWN_SURVEYS_DATE,EMAIL_OPTDOWN_PROMO,EMAIL_OPTDOWN_PROMO_DATE,EMAIL_OPTDOWN_SALON,EMAIL_OPTDOWN_SALON_DATE,EMAIL_OPTDOWN_REWARDS,EMAIL_OPTDOWN_REWARDS_DATE)
select stage.INDIVIDUAL_KEY,stage.INDIVIDUAL_ID,stage.FIRST_NAME,stage.LAST_NAME,stage.SALUTATION,stage.BIRTH_DATE,stage.DECEASED,stage.DO_NOT_MAIL,stage.GENDER,stage.LAST_NAME_SECONDARY,stage.LAST_PURCHASE_DATE,stage.MAIL_OPT_IN,stage.SIGN_UP_DATE,stage.CARD_NUMBER,stage.PRIMARY_INTERNATIONAL_ADDRESS,stage.SECONDARY_INTERNATIONAL_ADDRESS,stage.EMAIL_ACQUISITION_OPT_OUT,stage.PRIMARY_POSTAL_TOUCHPOINT_KEY,stage.PRIMARY_EMAIL_TOUCHPOINT_KEY,stage.PRIMARY_COMPLETE_PHONE_NUMBER,stage.MOBILE_COMPLETE_PHONE_NUMBER,stage.PRIMARY_CARD_TOUCHPOINT_KEY,stage.GENDER_SOURCE,stage.FINAL_GENDER,stage.DELETED_FLAG,stage.EMAIL_OPTDOWN_SURVEYS,stage.EMAIL_OPTDOWN_SURVEYS_DATE,stage.EMAIL_OPTDOWN_PROMO,stage.EMAIL_OPTDOWN_PROMO_DATE,stage.EMAIL_OPTDOWN_SALON,stage.EMAIL_OPTDOWN_SALON_DATE,stage.EMAIL_OPTDOWN_REWARDS,stage.EMAIL_OPTDOWN_REWARDS_DATE
from ulta_work.INDIVIDUAL_DIMENSION stage
LEFT OUTER JOIN
ulta_work.INDIVIDUAL_DIMENSION_UPDATED updated
on stage.INDIVIDUAL_ID = updated.INDIVIDUAL_ID
where updated.INDIVIDUAL_ID is null
UNION ALL
select INDIVIDUAL_KEY,INDIVIDUAL_ID,FIRST_NAME,LAST_NAME,SALUTATION,BIRTH_DATE,DECEASED,DO_NOT_MAIL,GENDER,LAST_NAME_SECONDARY,LAST_PURCHASE_DATE,MAIL_OPT_IN,SIGN_UP_DATE,CARD_NUMBER,PRIMARY_INTERNATIONAL_ADDRESS,SECONDARY_INTERNATIONAL_ADDRESS,EMAIL_ACQUISITION_OPT_OUT,PRIMARY_POSTAL_TOUCHPOINT_KEY,PRIMARY_EMAIL_TOUCHPOINT_KEY,PRIMARY_COMPLETE_PHONE_NUMBER,MOBILE_COMPLETE_PHONE_NUMBER,PRIMARY_CARD_TOUCHPOINT_KEY,GENDER_SOURCE,FINAL_GENDER,DELETED_FLAG,EMAIL_OPTDOWN_SURVEYS,EMAIL_OPTDOWN_SURVEYS_DATE,EMAIL_OPTDOWN_PROMO,EMAIL_OPTDOWN_PROMO_DATE,EMAIL_OPTDOWN_SALON,EMAIL_OPTDOWN_SALON_DATE,EMAIL_OPTDOWN_REWARDS,EMAIL_OPTDOWN_REWARDS_DATE
from ulta_work.INDIVIDUAL_DIMENSION_UPDATED
UNION ALL
select INDIVIDUAL_KEY,INDIVIDUAL_ID,FIRST_NAME,LAST_NAME,SALUTATION,BIRTH_DATE,DECEASED,DO_NOT_MAIL,GENDER,LAST_NAME_SECONDARY,LAST_PURCHASE_DATE,MAIL_OPT_IN,SIGN_UP_DATE,CARD_NUMBER,PRIMARY_INTERNATIONAL_ADDRESS,SECONDARY_INTERNATIONAL_ADDRESS,EMAIL_ACQUISITION_OPT_OUT,PRIMARY_POSTAL_TOUCHPOINT_KEY,PRIMARY_EMAIL_TOUCHPOINT_KEY,PRIMARY_COMPLETE_PHONE_NUMBER,MOBILE_COMPLETE_PHONE_NUMBER,PRIMARY_CARD_TOUCHPOINT_KEY,GENDER_SOURCE,FINAL_GENDER,DELETED_FLAG,EMAIL_OPTDOWN_SURVEYS,EMAIL_OPTDOWN_SURVEYS_DATE,EMAIL_OPTDOWN_PROMO,EMAIL_OPTDOWN_PROMO_DATE,EMAIL_OPTDOWN_SALON,EMAIL_OPTDOWN_SALON_DATE,EMAIL_OPTDOWN_REWARDS,EMAIL_OPTDOWN_REWARDS_DATE
from ulta_work.INDIVIDUAL_DIMENSION_UNCHANGED;

--5. Populate INDIVIDUAL_ID column table
DELETE ulta_work.RECIPIENTS_ID_SOURCES WHERE TRUE;

INSERT INTO ulta_work.RECIPIENTS_ID_SOURCES(RECIPIENT_ID,LOAD_DATE)
SELECT cast(REC.RECIPIENT_ID AS STRING) AS RECIPIENT_ID, CURRENT_TIMESTAMP AS LOAD_DATE FROM 
(SELECT EMAILOPTDOWN.IRECIPIENTID AS RECIPIENT_ID FROM ulta_incoming.EMAILOPTDOWN WHERE IRECIPIENTID <> 0 --AND IOPTINTYPEID = 14,13,12,15 is ignored  and only one is taken here
UNION DISTINCT
SELECT GIFTCARDHEADER.IPURCHASERECIPIENTID FROM ulta_incoming.GIFTCARDHEADER
UNION DISTINCT
SELECT GIFTCARDHEADER.IREDEEMRECIPIENTID FROM ulta_incoming.GIFTCARDHEADER 
UNION DISTINCT
SELECT INCIDENTS.IRECIPIENTID FROM ulta_incoming.INCIDENTS
UNION DISTINCT
SELECT LOYALTYACCOUNT.RECIPIENT_ID FROM ulta_incoming.LOYALTYACCOUNT WHERE IFNULL(CAST(RECIPIENT_ID as STRING),'') NOT IN ('', '0')
UNION DISTINCT
SELECT MESSAGING.RECIPIENT_ID FROM ulta_incoming.MESSAGING WHERE IFNULL(CAST(RECIPIENT_ID as STRING),'') NOT IN ('', '0')
UNION DISTINCT
SELECT ONLINEACCOUNTS.FK_RECIPIENT_ID FROM ulta_incoming.ONLINEACCOUNTS WHERE IFNULL(CAST(FK_RECIPIENT_ID as STRING),'') NOT IN ('', '0')
UNION DISTINCT
SELECT POINTSHEADER.FK_RECIPIENT_ID FROM ulta_incoming.POINTSHEADER WHERE IFNULL(CAST(FK_RECIPIENT_ID as STRING),'') NOT IN ('', '0')
UNION DISTINCT
SELECT POSTALADDRESS.RECIPIENT_ID FROM ulta_incoming.POSTALADDRESS WHERE IFNULL(CAST(RECIPIENT_ID as STRING),'') NOT IN ('', '0')
UNION DISTINCT
SELECT PREFERENCE.IRECIPIENTID FROM ulta_incoming.PREFERENCE
UNION DISTINCT
SELECT SALEDETAIL.RECIPIENT_ID FROM ulta_incoming.SALEDETAIL WHERE IFNULL(CAST(RECIPIENT_ID as STRING),'') NOT IN ('', '0')
UNION DISTINCT
SELECT SALONCUSTOMER.RECIPIENT_ID FROM ulta_incoming.SALONCUSTOMER WHERE IFNULL(CAST(RECIPIENT_ID as STRING),'') NOT IN ('', '0')
UNION DISTINCT
SELECT BROADLOGEMAIL.RECIPIENT_ID FROM ulta_incoming.BROADLOGEMAIL WHERE IFNULL(CAST(RECIPIENT_ID as STRING),'') NOT IN ('', '0')
UNION DISTINCT
SELECT TRACKINGLOGEMAIL.RECIPIENT_ID FROM ulta_incoming.TRACKINGLOGEMAIL WHERE IFNULL(CAST(RECIPIENT_ID as STRING),'') NOT IN ('', '0')
UNION DISTINCT
SELECT BROADLOGPOSTAL.RECIPIENT_ID FROM ulta_incoming.BROADLOGPOSTAL WHERE IFNULL(CAST(RECIPIENT_ID as STRING),'') NOT IN ('', '0')
UNION DISTINCT
SELECT EPSILON_INDIVIDUAL_DATA.INDIVIDUAL_ID FROM ulta_incoming.EPSILON_INDIVIDUAL_DATA
UNION DISTINCT
SELECT IRECIPIENTID FROM ulta_incoming.SURVEYDATA WHERE IFNULL(TRIM(SSURVEYID),'') NOT IN ('', '0')
UNION DISTINCT
SELECT CREDITCARDCUSTOMER.IRECIPIENTID FROM ulta_incoming.CREDITCARDCUSTOMER WHERE IRECIPIENTID is not null AND IRECIPIENTID <> 0
UNION DISTINCT
SELECT CREDITCARDPOINTSHEADER.ICUSTOMERID FROM ulta_incoming.CREDITCARDPOINTSHEADER WHERE IRECIPIENTID is not null AND IRECIPIENTID <> 0
UNION DISTINCT
SELECT DISCOUNTDETAIL.RECIPIENT_ID FROM ulta_incoming.DISCOUNTDETAIL WHERE IFNULL(CAST(RECIPIENT_ID as STRING),'') NOT IN ('', '0')
UNION DISTINCT
SELECT EMAILADDRESSES.FK_RECIPIENT_ID FROM ulta_incoming.EMAILADDRESSES WHERE IFNULL(CAST(FK_RECIPIENT_ID as STRING),'') NOT IN ('', '0')) REC
LEFT OUTER JOIN ulta_mart.INDIVIDUAL_DIMENSION IND ON CAST(REC.RECIPIENT_ID AS STRING) = IND.INDIVIDUAL_ID
WHERE IND.INDIVIDUAL_ID IS NULL;


--Update DELETED_FLAG for records in INDIVIDUAL_DIMENSION which are not present in RECIPIENTS_DEL
UPDATE ulta_mart.INDIVIDUAL_DIMENSION SET DELETED_FLAG = TRUE WHERE INDIVIDUAL_ID IN (
SELECT ID.INDIVIDUAL_ID
  FROM ulta_mart.INDIVIDUAL_DIMENSION ID
  LEFT OUTER JOIN ulta_incoming.RECIPIENTS_DEL RD
  ON ID.INDIVIDUAL_ID = cast(RD.RECIPIENT_ID AS string)
  WHERE RD.RECIPIENT_ID IS NULL and ID.DELETED_FLAG = FALSE
  );
  

