--DDL
bq mk -t ulta_base_offering.ITEM_META_DIMENSION ITEM_META_KEY:INTEGER,META_PRODUCT_ID:STRING,META_NAME:STRING,META_VALUE:STRING,CREATED_DATE:DATE,MODIFIED_DATE:DATE

bq mk -t ulta_base_offering.ITEM_META_DIMENSION_UNCHANGED ITEM_META_KEY:INTEGER,META_PRODUCT_ID:STRING,META_NAME:STRING,META_VALUE:STRING,CREATED_DATE:DATE,MODIFIED_DATE:DATE

bq mk -t ulta_mart_offering.ITEM_META_DIMENSION ITEM_META_KEY:INTEGER,META_PRODUCT_ID:STRING,META_NAME:STRING,META_VALUE:STRING,CREATED_DATE:DATE,MODIFIED_DATE:DATE


--1. Step to insert in to stage table
DELETE ulta_base_offering.ITEM_META_DIMENSION WHERE TRUE;


INSERT INTO ulta_base_offering.ITEM_META_DIMENSION(ITEM_META_KEY,META_PRODUCT_ID,META_NAME,META_VALUE,CREATED_DATE,MODIFIED_DATE)
SELECT 
NULL AS ITEM_META_KEY,
SPRODUCTID as META_PRODUCT_ID,
SNAME as META_NAME,
SVALUE as META_VALUE,
TSCREATED as CREATED_DATE,
TSLASTMODIFIED as MODIFIED_DATE
from ulta_land.PRODUCTMETA;



--2. populate unchanged stage table
DELETE ulta_base_offering.ITEM_META_DIMENSION_UNCHANGED WHERE TRUE;

INSERT INTO ulta_base_offering.ITEM_META_DIMENSION_UNCHANGED (ITEM_META_KEY,META_PRODUCT_ID,META_NAME,META_VALUE,CREATED_DATE,MODIFIED_DATE)
SELECT ITEM_META_KEY,META_PRODUCT_ID,META_NAME,META_VALUE,CREATED_DATE,MODIFIED_DATE
FROM ulta_mart_offering.ITEM_META_DIMENSION mart LEFT OUTER JOIN ulta_base_offering.ITEM_META_DIMENSION stage 
--ON mart.META_PRODUCT_ID = stage.META_PRODUCT_ID
--where stage.META_PRODUCT_ID is null; This cannot be used for key to filter.


--3. delete data from mart and take back up
bq cp ulta_mart_offering.ITEM_META_DIMENSION ulta_mart_offering.ITEM_META_DIMENSION_20180726
DELETE ulta_mart_offering.ITEM_META_DIMENSION WHERE TRUE;


--4. Populate mart table 

INSERT INTO ulta_mart_offering.ITEM_META_DIMENSION (ITEM_META_KEY,META_PRODUCT_ID,META_NAME,META_VALUE,CREATED_DATE,MODIFIED_DATE)
SELECT ITEM_META_KEY,META_PRODUCT_ID,META_NAME,META_VALUE,CREATED_DATE,MODIFIED_DATE
from ulta_base_offering.ITEM_META_DIMENSION
UNION ALL
SELECT ITEM_META_KEY,META_PRODUCT_ID,META_NAME,META_VALUE,CREATED_DATE,MODIFIED_DATE 
from ulta_base_offering.ITEM_META_DIMENSION_UNCHANGED;
