--DDL
bq mk -t ulta_work.POINTS_HEADER_FACT POINTS_HEADER_KEY:INTEGER,SALES_HEADER_KEY:INTEGER,POINTS_TRANSACTION_ID:INTEGER,LOYALTY_PERSONA_KEY:INTEGER,RECEIPT_AVAILABLE:NUMERIC,RECEIPT_BALANCE:NUMERIC,RECEIPT_BASE:NUMERIC,RECEIPT_BONUS:NUMERIC,RECEIPT_DEDUCTION:NUMERIC,RECEIPT_REDEEM:NUMERIC,REDEEM_VALUE:NUMERIC,TRANSACTION_DATE_KEY:INTEGER,TRANSACTION_NUMBER:INTEGER,TRANSACTION_STATUS:INTEGER,PROGRAM_MASTER_ID:STRING,TIER_NAME:STRING,TRANSACTION_DATETIME:TIMESTAMP,INDIVIDUAL_KEY:INTEGER,INDIVIDUAL_ID:STRING

bq mk -t ulta_work.POINTS_HEADER_FACT_UNCHANGED POINTS_HEADER_KEY:INTEGER,SALES_HEADER_KEY:INTEGER,POINTS_TRANSACTION_ID:INTEGER,LOYALTY_PERSONA_KEY:INTEGER,RECEIPT_AVAILABLE:NUMERIC,RECEIPT_BALANCE:NUMERIC,RECEIPT_BASE:NUMERIC,RECEIPT_BONUS:NUMERIC,RECEIPT_DEDUCTION:NUMERIC,RECEIPT_REDEEM:NUMERIC,REDEEM_VALUE:NUMERIC,TRANSACTION_DATE_KEY:INTEGER,TRANSACTION_NUMBER:INTEGER,TRANSACTION_STATUS:INTEGER,PROGRAM_MASTER_ID:STRING,TIER_NAME:STRING,TRANSACTION_DATETIME:TIMESTAMP,INDIVIDUAL_KEY:INTEGER,INDIVIDUAL_ID:STRING

bq mk -t ulta_mart.POINTS_HEADER_FACT POINTS_HEADER_KEY:INTEGER,SALES_HEADER_KEY:INTEGER,POINTS_TRANSACTION_ID:INTEGER,LOYALTY_PERSONA_KEY:INTEGER,RECEIPT_AVAILABLE:NUMERIC,RECEIPT_BALANCE:NUMERIC,RECEIPT_BASE:NUMERIC,RECEIPT_BONUS:NUMERIC,RECEIPT_DEDUCTION:NUMERIC,RECEIPT_REDEEM:NUMERIC,REDEEM_VALUE:NUMERIC,TRANSACTION_DATE_KEY:INTEGER,TRANSACTION_NUMBER:INTEGER,TRANSACTION_STATUS:INTEGER,PROGRAM_MASTER_ID:STRING,TIER_NAME:STRING,TRANSACTION_DATETIME:TIMESTAMP,INDIVIDUAL_KEY:INTEGER,INDIVIDUAL_ID:STRING

bq mk -t ulta_work.POINTS_HEADER_FACT_UPDATED POINTS_HEADER_KEY:INTEGER,SALES_HEADER_KEY:INTEGER,POINTS_TRANSACTION_ID:INTEGER,LOYALTY_PERSONA_KEY:INTEGER,RECEIPT_AVAILABLE:NUMERIC,RECEIPT_BALANCE:NUMERIC,RECEIPT_BASE:NUMERIC,RECEIPT_BONUS:NUMERIC,RECEIPT_DEDUCTION:NUMERIC,RECEIPT_REDEEM:NUMERIC,REDEEM_VALUE:NUMERIC,TRANSACTION_DATE_KEY:INTEGER,TRANSACTION_NUMBER:INTEGER,TRANSACTION_STATUS:INTEGER,PROGRAM_MASTER_ID:STRING,TIER_NAME:STRING,TRANSACTION_DATETIME:TIMESTAMP,INDIVIDUAL_KEY:INTEGER,INDIVIDUAL_ID:STRING

--1. Step to insert in to stage table
DELETE ulta_work.POINTS_HEADER_FACT WHERE TRUE;

INSERT INTO ulta_work.POINTS_HEADER_FACT(POINTS_HEADER_KEY,SALES_HEADER_KEY,POINTS_TRANSACTION_ID,LOYALTY_PERSONA_KEY,RECEIPT_AVAILABLE,RECEIPT_BALANCE,RECEIPT_BASE,RECEIPT_BONUS,RECEIPT_DEDUCTION,RECEIPT_REDEEM,REDEEM_VALUE,TRANSACTION_DATE_KEY,TRANSACTION_NUMBER,TRANSACTION_STATUS,PROGRAM_MASTER_ID,TIER_NAME,TRANSACTION_DATETIME,INDIVIDUAL_KEY,INDIVIDUAL_ID)
SELECT 
	NULL AS POINTS_HEADER_KEY,
	NULL AS SALES_HEADER_KEY,
	--CONCAT('SALES INTERACTIONS-SALES HEADER-',IFNULL(CAST(FK_SALEID AS STRING),''))AS SALES_HEADER_KEY,
	COALESCE(ph.TRANSACTION_ID) AS POINTS_TRANSACTION_ID,
	NULL AS LOYALTY_PERSONA_KEY,
	--CONCAT('CUSTOMER-LOYALTY-ACCOUNT-',IFNULL(CAST(CUSTOMER_ID AS STRING),''))AS LOYALTY_PERSONA_KEY,
	CAST(ph.RECEIPT_AVAILABLE AS NUMERIC) AS RECEIPT_AVAILABLE,--SUM(RECEIPT_AVAILABLE)
	CAST(ph.RECEIPT_BALANCE AS NUMERIC) AS RECEIPT_BALANCE,--SUM(RECEIPT_BALANCE)
	CAST(ph.RECEIPT_BASE AS NUMERIC) AS RECEIPT_BASE,--SUM(RECEIPT_BASE)
	CAST(ph.RECEIPT_BONUS AS NUMERIC) AS RECEIPT_BONUS,--SUM(RECEIPT_BONUS)
	CAST(ph.RECEIPT_DEDUCTION AS NUMERIC) AS RECEIPT_DEDUCTION,--SUM(RECEIPT_DEDUCTION)
	CAST(ph.RECEIPT_REDEEM AS NUMERIC) AS RECEIPT_REDEEM,--SUM(RECEIPT_REDEEM)
	CAST(ph.REDEEM_VALUE AS NUMERIC) AS REDEEM_VALUE,--SUM(REDEEM_VALUE)
	NULL AS TRANSACTION_DATE_KEY,--'CALENDAR-DATE-'||(SUBSTR(DECODE(TRANSACTION_DATE,'',NULL,TRANSACTION_DATE),1,10)::DATE)::VARCHAR(20)
	ph.TRANSACTION_NUMBER AS TRANSACTION_NUMBER,
	ph.TRANSACTION_STATUS AS TRANSACTION_STATUS,
	ph.PROGRAM_MASTER_ID AS PROGRAM_MASTER_ID,
	ph.TIER_NAME AS TIER_NAME,
	CAST(ph.TRANSACTION_DATE AS TIMESTAMP) AS TRANSACTION_DATETIME,--business day date
	NULL AS INDIVIDUAL_KEY,--Customer ID
	CAST(ph.FK_RECIPIENT_ID AS STRING) AS INDIVIDUAL_ID --CASE WHEN INDIVIDUAL_ID IN ('','0') THEN NULL ELSE DUMMY_INDIVIDUAL_KEY END
FROM
	(select * from (select *, row_number() over ( partition by transaction_id order by last_modified desc) as row_num from ulta_incoming.POINTSHEADER) where row_num = 1) ph
/*
LEFT JOIN
	(SELECT TRANSACTION_ID FROM ulta_incoming.POINTSDETAIL WHERE IFNULL(CAST(TRANSACTION_ID AS STRING),'') not in ('', '0') GROUP BY TRANSACTION_ID) pd
ON ph.TRANSACTION_ID = pd.TRANSACTION_ID
LEFT JOIN
	(SELECT TRANSACTION_ID FROM ulta_incoming.MESSAGING WHERE IFNULL(CAST(TRANSACTION_ID AS STRING),'') not in ('', '0') GROUP BY TRANSACTION_ID) ms
ON ph.TRANSACTION_ID = ms.TRANSACTION_ID
*/
--GROUP BY
--FK_SALEID,CUSTOMER_ID,TRANSACTION_NUMBER,TRANSACTION_STATUS,PROGRAM_MASTER_ID,TIER_NAME

--2. populate unchanged stage table
DELETE ulta_work.POINTS_HEADER_FACT_UNCHANGED WHERE TRUE;


INSERT INTO ulta_work.POINTS_HEADER_FACT_UNCHANGED (POINTS_HEADER_KEY,SALES_HEADER_KEY,POINTS_TRANSACTION_ID,LOYALTY_PERSONA_KEY,RECEIPT_AVAILABLE,RECEIPT_BALANCE,RECEIPT_BASE,RECEIPT_BONUS,RECEIPT_DEDUCTION,RECEIPT_REDEEM,REDEEM_VALUE,TRANSACTION_DATE_KEY,TRANSACTION_NUMBER,TRANSACTION_STATUS,PROGRAM_MASTER_ID,TIER_NAME,TRANSACTION_DATETIME,INDIVIDUAL_KEY,INDIVIDUAL_ID)
SELECT mart.POINTS_HEADER_KEY,mart.SALES_HEADER_KEY,mart.POINTS_TRANSACTION_ID,mart.LOYALTY_PERSONA_KEY,mart.RECEIPT_AVAILABLE,mart.RECEIPT_BALANCE,mart.RECEIPT_BASE,mart.RECEIPT_BONUS,mart.RECEIPT_DEDUCTION,mart.RECEIPT_REDEEM,mart.REDEEM_VALUE,mart.TRANSACTION_DATE_KEY,mart.TRANSACTION_NUMBER,mart.TRANSACTION_STATUS,mart.PROGRAM_MASTER_ID,mart.TIER_NAME,mart.TRANSACTION_DATETIME,mart.INDIVIDUAL_KEY,mart.INDIVIDUAL_ID
FROM 
ulta_mart.POINTS_HEADER_FACT mart LEFT OUTER JOIN ulta_work.POINTS_HEADER_FACT stage ON mart.POINTS_TRANSACTION_ID = stage.POINTS_TRANSACTION_ID AND stage.POINTS_TRANSACTION_ID IS NULL;


-- populate updated stage table
DELETE ulta_work.POINTS_HEADER_FACT_UPDATED WHERE TRUE;
	
	
INSERT INTO ulta_work.POINTS_HEADER_FACT_UPDATED (POINTS_HEADER_KEY,SALES_HEADER_KEY,POINTS_TRANSACTION_ID,LOYALTY_PERSONA_KEY,RECEIPT_AVAILABLE,RECEIPT_BALANCE,RECEIPT_BASE,RECEIPT_BONUS,RECEIPT_DEDUCTION,RECEIPT_REDEEM,REDEEM_VALUE,TRANSACTION_DATE_KEY,TRANSACTION_NUMBER,TRANSACTION_STATUS,PROGRAM_MASTER_ID,TIER_NAME,TRANSACTION_DATETIME,INDIVIDUAL_KEY,INDIVIDUAL_ID)
SELECT mart.POINTS_HEADER_KEY,stage.SALES_HEADER_KEY,stage.POINTS_TRANSACTION_ID,stage.LOYALTY_PERSONA_KEY,stage.RECEIPT_AVAILABLE,stage.RECEIPT_BALANCE,stage.RECEIPT_BASE,stage.RECEIPT_BONUS,stage.RECEIPT_DEDUCTION,stage.RECEIPT_REDEEM,stage.REDEEM_VALUE,stage.TRANSACTION_DATE_KEY,stage.TRANSACTION_NUMBER,stage.TRANSACTION_STATUS,stage.PROGRAM_MASTER_ID,stage.TIER_NAME,stage.TRANSACTION_DATETIME,stage.INDIVIDUAL_KEY,stage.INDIVIDUAL_ID
FROM 
ulta_mart.POINTS_HEADER_FACT mart INNER JOIN ulta_work.POINTS_HEADER_FACT stage ON mart.POINTS_TRANSACTION_ID = stage.POINTS_TRANSACTION_ID;

--3. delete data from mart 
bq cp ulta_mart.POINTS_HEADER_FACT ulta_mart.POINTS_HEADER_FACT_20180727
DELETE ulta_mart.POINTS_HEADER_FACT WHERE TRUE;


--4. Populate mart table

INSERT INTO ulta_mart.POINTS_HEADER_FACT(POINTS_HEADER_KEY,SALES_HEADER_KEY,POINTS_TRANSACTION_ID,LOYALTY_PERSONA_KEY,RECEIPT_AVAILABLE,RECEIPT_BALANCE,RECEIPT_BASE,RECEIPT_BONUS,RECEIPT_DEDUCTION,RECEIPT_REDEEM,REDEEM_VALUE,TRANSACTION_DATE_KEY,TRANSACTION_NUMBER,TRANSACTION_STATUS,PROGRAM_MASTER_ID,TIER_NAME,TRANSACTION_DATETIME,INDIVIDUAL_KEY,INDIVIDUAL_ID)
SELECT stage.POINTS_HEADER_KEY,stage.SALES_HEADER_KEY,stage.POINTS_TRANSACTION_ID,stage.LOYALTY_PERSONA_KEY,stage.RECEIPT_AVAILABLE,stage.RECEIPT_BALANCE,stage.RECEIPT_BASE,stage.RECEIPT_BONUS,stage.RECEIPT_DEDUCTION,stage.RECEIPT_REDEEM,stage.REDEEM_VALUE,stage.TRANSACTION_DATE_KEY,stage.TRANSACTION_NUMBER,stage.TRANSACTION_STATUS,stage.PROGRAM_MASTER_ID,stage.TIER_NAME,stage.TRANSACTION_DATETIME,stage.INDIVIDUAL_KEY,stage.INDIVIDUAL_ID
FROM ulta_work.POINTS_HEADER_FACT stage
left join ulta_work.POINTS_HEADER_FACT_UPDATED updated
on stage.POINTS_TRANSACTION_ID = updated.POINTS_TRANSACTION_ID
where updated.POINTS_TRANSACTION_ID is null
UNION ALL
select POINTS_HEADER_KEY,SALES_HEADER_KEY,POINTS_TRANSACTION_ID,LOYALTY_PERSONA_KEY,RECEIPT_AVAILABLE,RECEIPT_BALANCE,RECEIPT_BASE,RECEIPT_BONUS,RECEIPT_DEDUCTION,RECEIPT_REDEEM,REDEEM_VALUE,TRANSACTION_DATE_KEY,TRANSACTION_NUMBER,TRANSACTION_STATUS,PROGRAM_MASTER_ID,TIER_NAME,TRANSACTION_DATETIME,INDIVIDUAL_KEY,INDIVIDUAL_ID
from ulta_work.POINTS_HEADER_FACT_UPDATED
UNION ALL
SELECT POINTS_HEADER_KEY,SALES_HEADER_KEY,POINTS_TRANSACTION_ID,LOYALTY_PERSONA_KEY,RECEIPT_AVAILABLE,RECEIPT_BALANCE,RECEIPT_BASE,RECEIPT_BONUS,RECEIPT_DEDUCTION,RECEIPT_REDEEM,REDEEM_VALUE,TRANSACTION_DATE_KEY,TRANSACTION_NUMBER,TRANSACTION_STATUS,PROGRAM_MASTER_ID,TIER_NAME,TRANSACTION_DATETIME,INDIVIDUAL_KEY,INDIVIDUAL_ID
FROM ulta_work.POINTS_HEADER_FACT_UNCHANGED;
